const STORAGE_KEY = 'memphis-fleet-desktop-v1';
const now = Date.now();
const SERVERS = ['New York','Detroit','Chicago','San Francisco','Atlanta','San Diego','Los Angeles','Miami','Las Vegas','Washington','Dallas','Boston','Houston','Seattle','Phoenix','Denver','Portland','Orlando','Memphis'];
const blankProfile = (id='profile-1',name='Персонаж 1',server='Memphis') => ({id,name,server,cash:0,vehicles:[],rentals:[],rentalHistory:[],deals:[]});
const seed = {activeServer:'Memphis',activeProfileId:'profile-1',profiles:[blankProfile()]};
let database = load();
let state = getActiveProfile();
let currentFilter = 'all';
let catalogCategory = 'all';
let catalogPage = 1;
const CATALOG_PAGE_SIZE = 24;
const categorySets = Object.fromEntries(Object.entries(window.VEHICLE_CATEGORIES||{}).map(([key,ids])=>[key,new Set(ids)]));

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const money = n => '$' + Math.round(Number(n)||0).toLocaleString('ru-RU');
const mc = n => Math.round(Number(n)||0).toLocaleString('ru-RU') + ' MC';
const purchaseMoney = v => v?.purchaseCurrency==='mc'?mc(v.purchase):money(v?.purchase);
const dealMoney = d => d?.currency==='mc'?mc(d.amount):money(d?.amount);
const vehicleValue = v => +v.govPrice||+v.market||(v.purchaseCurrency==='mc'?0:+v.purchase||0);
const parseMoney = value => Number(String(value??'').replace(/[^\d]/g,''))||0;
const inputMoney = value => value===''||value==null?'':Math.round(Number(value)||0).toLocaleString('ru-RU');
const uid = p => p + Date.now().toString(36) + Math.random().toString(36).slice(2,7);
const statusName = s => ({available:'Свободна',rented:'В аренде',sale:'На продаже',personal:'Личная'}[s]||s);
const vehicle = id => state.vehicles.find(v=>v.id===id);
const esc = value => String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));

function normalizeVehicle(v){return{purchaseCurrency:'money',govPrice:0,...v}}
function normalizeDatabase(saved){if(saved?.profiles?.length){const profiles=saved.profiles.map(p=>{const profile={...blankProfile(p.id,p.name,p.server||'Memphis'),...p,server:p.server||'Memphis'};profile.vehicles=(profile.vehicles||[]).map(normalizeVehicle);return profile});const selected=profiles.find(p=>p.id===saved.activeProfileId);const activeServer=saved.activeServer||selected?.server||'Memphis';let activeProfileId=selected?.server===activeServer?selected.id:profiles.find(p=>p.server===activeServer)?.id;if(!activeProfileId){const profile=blankProfile(uid('p'),'Персонаж 1',activeServer);profiles.push(profile);activeProfileId=profile.id}return{...saved,activeServer,activeProfileId,profiles}}const legacy={...blankProfile(),...(saved||{})};legacy.id='profile-1';legacy.name='Персонаж 1';legacy.server='Memphis';legacy.vehicles=(legacy.vehicles||[]).map(v=>normalizeVehicle({...v,advert:['vrs6','vlc'].includes(v.id)?'':(v.advert||'')}));return{activeServer:'Memphis',activeProfileId:legacy.id,profiles:[legacy]}}
function load(){try{return normalizeDatabase(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return structuredClone(seed)}}
function getActiveProfile(){return database.profiles.find(p=>p.id===database.activeProfileId&&p.server===database.activeServer)||database.profiles.find(p=>p.server===database.activeServer)||database.profiles[0]}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(database));renderAll()}
function img(v,cls=''){return v?.photo?`<img class="${cls}" src="${v.photo}" alt="${v.name}">`:`<div class="car-placeholder ${cls}">${(v?.name||'AUTO').split(' ').slice(-1)[0].slice(0,3).toUpperCase()}</div>`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

function renderAll(){
  const fleetValue=state.vehicles.reduce((s,v)=>s+vehicleValue(v),0);
  const rentIncome=state.deals.filter(d=>d.type==='income'&&/аренд/i.test(d.note)).reduce((s,d)=>s+(+d.amount||0),0);
  $('#headerCash').textContent=money(state.cash);
  $('#serverSelect').innerHTML=SERVERS.map(server=>`<option value="${server}" ${server===database.activeServer?'selected':''}>${server}</option>`).join('');
  $('#profileSelect').innerHTML=database.profiles.filter(p=>p.server===database.activeServer).map(p=>`<option value="${p.id}" ${p.id===database.activeProfileId?'selected':''}>${esc(p.name)}</option>`).join('');
  $('#stats').innerHTML=[
    ['Свободный баланс',money(state.cash),'Доступно для новых сделок','rgba(47,212,167,.14)'],
    ['Стоимость автопарка',money(fleetValue),`${state.vehicles.length} автомобилей`,'rgba(91,140,255,.14)'],
    ['Активные аренды',state.rentals.length,`${money(rentIncome)} заработано`,'rgba(255,189,89,.14)']
  ].map(x=>`<div class="stat" style="--glow:${x[3]}"><span class="stat-label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
  renderGarage();renderRentals();renderDeals();renderDashboard();fillVehicleSelects();
}

function renderDashboard(){
  $('#vehicleStrip').innerHTML=state.vehicles.slice(0,4).map(v=>`<div class="mini-car"><span class="status ${v.status}">${statusName(v.status)}</span>${img(v)}<div class="mini-body"><b>${v.name}</b><small>${v.govPrice?`Гос. ${money(v.govPrice)}`:purchaseMoney(v)}</small></div></div>`).join('')||'<div class="empty">Добавьте первую машину</div>';
  $('#dashboardRentals').innerHTML=state.rentals.slice(0,3).map(r=>rentalMini(r)).join('')||'<div class="empty">Сейчас все машины свободны</div>';
  const deals=[...state.deals].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  $('#recentActivity').innerHTML=deals.map(d=>`<div class="activity"><small>${d.date}</small><span>${dealType(d.type)}</span><b>${vehicle(d.vehicleId)?.name||d.vehicleName||'Без автомобиля'}</b><strong class="amount ${['income','sale','scrapSale'].includes(d.type)?'positive':'negative'}">${['income','sale','scrapSale'].includes(d.type)?'+':'−'}${dealMoney(d)}</strong></div>`).join('')||'<div class="empty">Операций пока нет</div>';
}

function renderGarage(){
  const q=$('#garageSearch')?.value?.toLowerCase()||'';
  const list=state.vehicles.filter(v=>(currentFilter==='all'||v.status===currentFilter)&&(`${v.name} ${v.plate}`.toLowerCase().includes(q)));
  $('#garageGrid').innerHTML=list.map(v=>`<article class="car-card"><span class="status ${v.status}">${statusName(v.status)}</span>${v.purchaseCurrency==='mc'?'<span class="mc-badge">MC</span>':''}${img(v)}<div class="car-body"><div class="car-title"><div><b>${esc(v.name)}</b><small>${esc(v.plate||'Без номера')}</small></div><span class="car-value">${v.govPrice?money(v.govPrice):'Госцена не указана'}</span></div><div class="car-metrics"><div class="metric"><small>ПОКУПКА</small><b>${purchaseMoney(v)}</b></div><div class="metric"><small>ГОС. ЦЕНА</small><b>${v.govPrice?money(v.govPrice):'—'}</b></div><div class="metric"><small>СВАЛКА</small><b>${money(v.scrap)}</b></div></div><div class="card-ad-editor"><label for="ad-${v.id}">ТЕКСТ ОБЪЯВЛЕНИЯ</label><textarea id="ad-${v.id}" data-ad-input="${v.id}" rows="3" placeholder="Введите текст объявления">${esc(v.advert)}</textarea><div><button data-save-ad="${v.id}">Сохранить текст</button><button class="copy-action" data-copy-ad="${v.id}" ${v.advert?'':'disabled'}>Копировать</button></div></div><div class="card-actions"><button data-rent="${v.id}" ${v.status==='rented'?'disabled':''}>В аренду</button><button data-edit-car="${v.id}">Изменить</button><button class="danger" data-delete-car="${v.id}">Удалить</button></div></div></article>`).join('')||'<div class="empty">Ничего не найдено</div>';
}

function rentalMini(r){const v=vehicle(r.vehicleId);const pct=Math.max(0,Math.min(100,(r.end-Date.now())/(r.end-r.start)*100));return `<div class="rental-mini"><div class="row-between"><div><b>${v?.name||'Транспорт'}</b><small> • ${money(r.price)} / ${r.unit==='day'?'сутки':'час'}</small></div><span class="timer" data-end="${r.end}"></span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
function renderRentals(){
  $('#rentalList').innerHTML=state.rentals.map(r=>{const v=vehicle(r.vehicleId);return `<article class="rental-card">${img(v,'rent-thumb')}<div><h3>${v?.name||'Транспорт'}</h3><p>${money(r.price)} / ${r.unit==='day'?'сутки':'час'} • ${r.duration||Math.round(r.hours/(r.unit==='day'?24:1))} ${r.unit==='day'?'сут.':'ч.'}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,(r.end-Date.now())/(r.end-r.start)*100))}%"></i></div></div><div class="rental-actions"><span class="timer" data-end="${r.end}"></span><button data-extend="${r.id}">+24 часа</button><button data-return="${r.id}">Возвращена</button></div></article>`}).join('')||'<div class="empty">Активной аренды нет</div>';
  $('#rentalHistory').innerHTML=state.rentalHistory.slice().reverse().slice(0,12).map(r=>`<div class="history-item"><div class="row-between"><b>${r.vehicleName}</b><strong class="amount positive">+${money(r.total||r.price)}</strong></div><small>${new Date(r.returned).toLocaleString('ru-RU')}</small></div>`).join('')||'<div class="empty">История пока пустая</div>';
}

function dealType(t){return({income:'Доход',expense:'Расход',purchase:'Покупка',sale:'Продажа игроку',scrapSale:'Продажа на свалку'}[t]||t)}
function renderDeals(){
  const dollarDeals=state.deals.filter(d=>d.currency!=='mc');
  const inc=dollarDeals.filter(d=>['income','sale','scrapSale'].includes(d.type)).reduce((s,d)=>s+(+d.amount||0),0);
  const out=dollarDeals.filter(d=>['expense','purchase'].includes(d.type)).reduce((s,d)=>s+(+d.amount||0),0);
  $('#dealSummary').innerHTML=`<div class="deal-chip"><small>Доходы</small><b class="amount positive">${money(inc)}</b></div><div class="deal-chip"><small>Расходы</small><b class="amount negative">${money(out)}</b></div><div class="deal-chip"><small>Результат</small><b>${money(inc-out)}</b></div>`;
  $('#dealTable').innerHTML=state.deals.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(d=>`<tr><td>${d.date}</td><td>${dealType(d.type)}</td><td>${vehicle(d.vehicleId)?.name||d.vehicleName||'—'}</td><td>${d.note||'—'}</td><td class="amount ${['income','sale','scrapSale'].includes(d.type)?'positive':'negative'}">${['income','sale','scrapSale'].includes(d.type)?'+':'−'}${dealMoney(d)}</td><td><button class="icon-btn danger" data-delete-deal="${d.id}">×</button></td></tr>`).join('');
}

function fillVehicleSelects(){
  $('#dealVehicle').innerHTML='<option value="">Без автомобиля</option>'+state.vehicles.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');
  $('#rentalCarPicker').innerHTML=state.vehicles.filter(v=>v.status!=='rented').map(v=>`<button type="button" class="pick-car" data-pick="${v.id}">${img(v)}<b>${v.name}</b></button>`).join('')||'<div class="empty">Нет свободных машин</div>';
}

function updateTimers(){
  $$('[data-end]').forEach(el=>{const ms=+el.dataset.end-Date.now();if(ms<=0){el.textContent='Просрочено';el.style.color='var(--red)';return}const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1000);el.textContent=`${h}ч ${String(m).padStart(2,'0')}м ${String(s).padStart(2,'0')}с`});
}

function openRental(id){fillVehicleSelects();const form=$('#rentalForm');form.reset();form.elements.namedItem('vehicleId').value=id||'';setRentalUnit('hour');$$('.pick-car').forEach(b=>b.classList.toggle('selected',b.dataset.pick===id));syncRentalAd();$('#rentalDialog').showModal()}
function syncRentalAd(){const id=$('#rentalForm').elements.namedItem('vehicleId').value;const v=vehicle(id);$('#rentalAdBox span').textContent=v?.advert||'У выбранной машины пока нет шаблона';$('#copyRentalAd').disabled=!v?.advert}
async function copyAdvert(id){const text=vehicle(id)?.advert;if(!text)return toast('Сначала добавьте текст объявления');try{await navigator.clipboard.writeText(text);toast('Объявление скопировано')}catch{toast('Не удалось скопировать текст')}}
function catalogPrices(id){return (window.VEHICLE_PRICES||{})[id]||{}}
function syncVehiclePrices({preserveMcScrap=false}={}){const f=$('#vehicleForm'),field=name=>f.elements.namedItem(name),currency=field('purchaseCurrency').value,prices=catalogPrices(field('catalogId').value),gov=+prices.govPrice||parseMoney(field('govPrice').value);field('govPrice').value=inputMoney(gov);field('govPrice').readOnly=true;if(currency==='money'){field('scrap').value=inputMoney(Math.round(gov*.5));field('scrap').readOnly=true;field('scrap').placeholder='50% государственной цены';field('scrap').title='Для обычной техники цена свалки рассчитывается как 50% государственной цены'}else{const officialScrap=+prices.mcScrapPrice||+prices.scrapPrice||0;if(officialScrap)field('scrap').value=inputMoney(officialScrap);else if(!preserveMcScrap)field('scrap').value='';field('scrap').readOnly=!!officialScrap;field('scrap').placeholder=officialScrap?'Цена из Wiki':'Введите цену свалки для MC';field('scrap').title=officialScrap?'Официальная цена свалки из Wiki':'Для MC-техники цена свалки задаётся отдельно'}}
function setPurchaseCurrency(currency,{preserveMcScrap=false}={}){const f=$('#vehicleForm');f.elements.namedItem('purchaseCurrency').value=currency;$$('[data-purchase-currency]').forEach(b=>b.classList.toggle('active',b.dataset.purchaseCurrency===currency));$('#purchasePriceLabel').childNodes[0].nodeValue=currency==='mc'?'Цена покупки, MC':'Цена покупки, $';$('#mcPurchaseHint').hidden=currency!=='mc';if(currency==='mc'&&f.elements.namedItem('status').value==='sale')f.elements.namedItem('status').value='available';syncVehiclePrices({preserveMcScrap})}
function openVehicle(v){const f=$('#vehicleForm'),field=name=>f.elements.namedItem(name);f.reset();$('#vehicleDialogTitle').textContent=v?'Изменить транспорт':'Добавить транспорт';field('editId').value=v?.id||'';field('catalogId').value=v?.catalogId||'';field('vehicleType').value=v?.vehicleType||'car';field('name').value=v?.name||'';field('plate').value=v?.plate||'';field('purchase').value=inputMoney(v?.purchase);field('govPrice').value=inputMoney(v?.govPrice);field('scrap').value=inputMoney(v?.scrap);field('status').value=v?.status||'available';setPurchaseCurrency(v?.purchaseCurrency||'money',{preserveMcScrap:!!v});$('#photoData').value=v?.photo||'';$('#photoPreview').innerHTML=v?.photo?`<img src="${v.photo}" alt="Фото транспорта">`:'<span>＋</span><b>Выбрать транспорт из каталога</b><small>956 позиций</small>';$('#vehicleDialog').showModal()}

function catalogType(id){for(const type of ['moto','bmx','boat','heli','air','commercial'])if(categorySets[type]?.has(id))return type;return 'car'}
function renderCatalog(){const q=$('#catalogSearch').value.trim().toLowerCase();const filtered=(window.VEHICLE_CATALOG||[]).filter(item=>(catalogCategory==='all'||catalogType(item.id)===catalogCategory)&&item.name.toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(filtered.length/CATALOG_PAGE_SIZE));catalogPage=Math.min(catalogPage,pages);const start=(catalogPage-1)*CATALOG_PAGE_SIZE;$('#catalogGrid').innerHTML=filtered.slice(start,start+CATALOG_PAGE_SIZE).map(item=>`<button type="button" class="catalog-card" data-catalog-id="${esc(item.id)}"><div><img loading="lazy" src="${esc(item.image)}" alt="${esc(item.name)}"><span>${esc(item.name).split(' ').slice(-1)[0].slice(0,3).toUpperCase()}</span></div><b>${esc(item.name)}</b><small>${({car:'Автомобиль',commercial:'Коммерческий',moto:'Мотоцикл',bmx:'Велосипед',boat:'Водный транспорт',heli:'Вертолёт',air:'Самолёт'})[catalogType(item.id)]}</small></button>`).join('')||'<div class="empty">Ничего не найдено</div>';$('#catalogCount').textContent=`Найдено: ${filtered.length}`;$('#catalogPage').textContent=`${catalogPage} / ${pages}`;$('#catalogPrev').disabled=catalogPage<=1;$('#catalogNext').disabled=catalogPage>=pages}
function openCatalog(){catalogPage=1;$('#catalogSearch').value='';renderCatalog();$('#catalogDialog').showModal()}
function selectCatalogItem(id){const item=(window.VEHICLE_CATALOG||[]).find(x=>x.id===id);if(!item)return;const f=$('#vehicleForm');f.elements.namedItem('catalogId').value=item.id;f.elements.namedItem('vehicleType').value=catalogType(item.id);f.elements.namedItem('name').value=item.name;const prices=catalogPrices(item.id);f.elements.namedItem('govPrice').value=inputMoney(prices.govPrice);syncVehiclePrices();$('#photoData').value=item.image;$('#photoPreview').innerHTML=`<img src="${item.image}" alt="${esc(item.name)}">`;$('#catalogDialog').close();toast(prices.govPrice?'Транспорт и госцена выбраны':'Транспорт выбран — госцена пока не найдена')}

function setRentalUnit(unit){const form=$('#rentalForm'),daily=unit==='day',max=daily?30:48;form.elements.namedItem('unit').value=unit;$$('[data-rental-unit]').forEach(b=>b.classList.toggle('active',b.dataset.rentalUnit===unit));$('#rentalPriceLabel').childNodes[0].nodeValue=daily?'Цена за сутки':'Цена за час';$('#rentalDurationLabel').childNodes[0].nodeValue=daily?'Количество суток':'Количество часов';const duration=form.elements.namedItem('duration');duration.max=max;duration.value=1}

$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active');$('#viewTitle').textContent=({dashboard:'Главная',garage:'Ваш автопарк',rentals:'Центр аренды',deals:'Финансовый журнал',photos:'Редактор фотографий'}[b.dataset.view])});
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){close.closest('dialog')?.close();return}const jump=e.target.closest('[data-jump]');if(jump)$(`.nav-item[data-view="${jump.dataset.jump}"]`).click();const rent=e.target.closest('[data-rent]');if(rent&&!rent.disabled)openRental(rent.dataset.rent);const edit=e.target.closest('[data-edit-car]');if(edit)openVehicle(vehicle(edit.dataset.editCar));const saveAd=e.target.closest('[data-save-ad]');if(saveAd){const v=vehicle(saveAd.dataset.saveAd);if(v){v.advert=$(`[data-ad-input="${v.id}"]`).value.trim();save();toast('Текст объявления сохранён')}return}const copy=e.target.closest('[data-copy-ad]');if(copy&&!copy.disabled)copyAdvert(copy.dataset.copyAd);const del=e.target.closest('[data-delete-car]');if(del&&confirm('Удалить автомобиль из гаража?')){state.vehicles=state.vehicles.filter(v=>v.id!==del.dataset.deleteCar);save()}const ret=e.target.closest('[data-return]');if(ret)returnRental(ret.dataset.return);const ext=e.target.closest('[data-extend]');if(ext){const r=state.rentals.find(x=>x.id===ext.dataset.extend);r.end+=864e5;save();toast('Аренда продлена на 24 часа')}const dd=e.target.closest('[data-delete-deal]');if(dd&&confirm('Удалить операцию?')){state.deals=state.deals.filter(d=>d.id!==dd.dataset.deleteDeal);save()}});
document.addEventListener('input',e=>{if(!e.target.matches('[data-money]'))return;const digits=e.target.value.replace(/\D/g,'');e.target.value=digits?Number(digits).toLocaleString('ru-RU'):''});
$('#garageSearch').addEventListener('input',renderGarage);$('#garageFilter').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;currentFilter=b.dataset.filter;$$('#garageFilter button').forEach(x=>x.classList.toggle('active',x===b));renderGarage()});
$('#quickAdd').addEventListener('click',()=>openVehicle());
$$('[data-purchase-currency]').forEach(b=>b.addEventListener('click',()=>setPurchaseCurrency(b.dataset.purchaseCurrency)));
$('#photoPreview').addEventListener('click',openCatalog);$('#openCatalogBtn').addEventListener('click',openCatalog);$('#uploadOwnPhoto').addEventListener('click',()=>$('#vehiclePhoto').click());$('#vehiclePhoto').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#photoData').value=r.result;$('#photoPreview').innerHTML=`<img src="${r.result}" alt="Фото транспорта">`};r.readAsDataURL(f)});
$('#catalogFilters [data-category="moto"]').insertAdjacentHTML('afterend','<button data-category="bmx">Велосипеды</button>');
$('#catalogSearch').addEventListener('input',()=>{catalogPage=1;renderCatalog()});$('#catalogFilters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;catalogCategory=b.dataset.category;catalogPage=1;$$('#catalogFilters button').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$('#catalogGrid').addEventListener('click',e=>{const b=e.target.closest('[data-catalog-id]');if(b)selectCatalogItem(b.dataset.catalogId)});$('#catalogPrev').addEventListener('click',()=>{catalogPage--;renderCatalog()});$('#catalogNext').addEventListener('click',()=>{catalogPage++;renderCatalog()});
$('#vehicleForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),purchase=parseMoney(d.purchase),govPrice=parseMoney(d.govPrice),scrap=parseMoney(d.scrap),purchaseCurrency=d.purchaseCurrency==='mc'?'mc':'money';if(!d.catalogId&&!d.editId)return toast('Сначала выберите транспорт из каталога');if(purchaseCurrency==='mc'&&d.status==='sale')return toast('MC-технику нельзя выставить на продажу игрокам');if(d.editId){const current=vehicle(d.editId);Object.assign(current,{catalogId:d.catalogId,vehicleType:d.vehicleType,name:d.name,plate:d.plate,purchase,purchaseCurrency,govPrice,scrap,status:d.status,photo:$('#photoData').value});toast('Карточка обновлена')}else{state.vehicles.push({id:uid('v'),catalogId:d.catalogId,vehicleType:d.vehicleType,name:d.name,plate:d.plate,purchase,purchaseCurrency,govPrice,scrap,status:d.status,photo:$('#photoData').value,advert:''});if(purchaseCurrency!=='mc')state.cash-=purchase;state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'purchase',vehicleId:state.vehicles.at(-1).id,vehicleName:d.name,amount:purchase,currency:purchaseCurrency,note:purchaseCurrency==='mc'?'Покупка транспорта за Majestic Coin':'Покупка транспорта'});toast(purchaseCurrency==='mc'?'MC-транспорт добавлен':'Транспорт добавлен')}$('#vehicleDialog').close();save()});
$('#newRentalBtn').addEventListener('click',()=>openRental());$('#rentalCarPicker').addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(!b)return;$('#rentalForm').elements.namedItem('vehicleId').value=b.dataset.pick;$$('.pick-car').forEach(x=>x.classList.toggle('selected',x===b));syncRentalAd()});$('#copyRentalAd').addEventListener('click',()=>copyAdvert($('#rentalForm').elements.namedItem('vehicleId').value));
$$('[data-rental-unit]').forEach(b=>b.addEventListener('click',()=>setRentalUnit(b.dataset.rentalUnit)));
$('#rentalForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.vehicleId)return toast('Сначала выберите транспорт');const selected=vehicle(d.vehicleId);if(!selected)return toast('Транспорт не найден');const start=Date.now(),duration=+d.duration,hours=duration*(d.unit==='day'?24:1),price=parseMoney(d.price),total=price*duration;state.rentals.push({id:uid('r'),vehicleId:d.vehicleId,price,total,duration,unit:d.unit,hours,start,end:start+(hours*36e5)});selected.status='rented';$('#rentalDialog').close();save();toast('Аренда запущена')});
function returnRental(id){const r=state.rentals.find(x=>x.id===id);if(!r)return;const v=vehicle(r.vehicleId);if(v)v.status='available';const total=r.total||r.price;state.rentalHistory.push({...r,total,vehicleName:v?.name||'Транспорт',returned:Date.now()});state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'income',vehicleId:r.vehicleId,amount:total,note:'Доход от аренды'});state.cash+=total;state.rentals=state.rentals.filter(x=>x.id!==id);save();toast('Транспорт возвращён, доход записан')}
function syncDealAmount(){const form=$('#dealForm'),type=form.elements.namedItem('type').value,sold=vehicle(form.elements.namedItem('vehicleId').value);if(type==='scrapSale'&&sold)form.elements.namedItem('amount').value=inputMoney(sold.scrap)}
$('#newDealBtn').addEventListener('click',()=>{const form=$('#dealForm');form.reset();form.elements.namedItem('date').value=new Date().toISOString().slice(0,10);$('#dealDialog').showModal()});
$('#dealForm').elements.namedItem('type').addEventListener('change',syncDealAmount);$('#dealVehicle').addEventListener('change',syncDealAmount);
$('#dealForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),amount=parseMoney(d.amount),sold=vehicle(d.vehicleId),removesVehicle=['sale','scrapSale'].includes(d.type);if(d.type==='sale'&&sold?.purchaseCurrency==='mc')return toast('MC-технику можно продать только на свалку');if(d.type==='scrapSale'&&!sold)return toast('Выберите транспорт для продажи на свалку');state.deals.push({id:uid('d'),...d,amount,vehicleName:sold?.name||'',note:d.note||(d.type==='scrapSale'?'Продажа транспорта на свалку':'')});state.cash+=['income','sale','scrapSale'].includes(d.type)?amount:-amount;if(removesVehicle&&sold){state.rentals=state.rentals.filter(r=>r.vehicleId!==sold.id);state.vehicles=state.vehicles.filter(v=>v.id!==sold.id)}$('#dealDialog').close();save();toast(removesVehicle&&sold?(d.type==='scrapSale'?'Транспорт продан на свалку и удалён из гаража':'Продажа записана, транспорт удалён из гаража'):'Операция добавлена')});
$('#profileSelect').addEventListener('change',e=>{database.activeProfileId=e.target.value;state=getActiveProfile();save();toast(`Профиль «${state.name}» открыт`)});
$('#serverSelect').addEventListener('change',e=>{database.activeServer=e.target.value;let profile=database.profiles.find(p=>p.server===database.activeServer);if(!profile){profile=blankProfile(uid('p'),'Персонаж 1',database.activeServer);database.profiles.push(profile)}database.activeProfileId=profile.id;state=profile;save();toast(`Сервер ${database.activeServer} открыт`)});
$('#addProfileBtn').addEventListener('click',()=>{const form=$('#profileForm');form.reset();$('#profileDialog').showModal();requestAnimationFrame(()=>form.elements.namedItem('name').focus())});
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.target).get('name')?.trim();if(!name)return;const profile=blankProfile(uid('p'),name,database.activeServer);database.profiles.push(profile);database.activeProfileId=profile.id;state=profile;$('#profileDialog').close();save();toast('Персонаж добавлен')});
$('#editBalanceBtn').addEventListener('click',()=>{const input=$('#balanceForm').elements.namedItem('amount');input.value=inputMoney(state.cash);$('#balanceDialog').showModal();requestAnimationFrame(()=>input.select())});
$('#balanceForm').addEventListener('submit',e=>{e.preventDefault();const amount=parseMoney(new FormData(e.target).get('amount'));state.cash=amount;$('#balanceDialog').close();save();toast('Баланс обновлён')});
$('#resetProfileBtn').addEventListener('click',()=>{if(!confirm(`Сбросить всю статистику персонажа «${state.name}»? Это удалит баланс, гараж, аренды и сделки.`))return;const index=database.profiles.findIndex(p=>p.id===state.id);database.profiles[index]=blankProfile(state.id,state.name,state.server);state=database.profiles[index];save();toast('Статистика персонажа сброшена')});
$('#exportBtn').addEventListener('click',async()=>{const text=JSON.stringify(database,null,2);if(window.desktop)await window.desktop.saveBackup(text);else{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download='fleet-desk.json';a.click()}toast('Резервная копия сохранена')});
$('#importBtn').addEventListener('click',async()=>{let text=window.desktop?await window.desktop.openBackup():null;if(!text)return;try{database=normalizeDatabase(JSON.parse(text));state=getActiveProfile();save();toast('База восстановлена')}catch{toast('Не удалось прочитать файл')}});

const updateLabels={checking:'Проверяем обновления…',available:'Найдена новая версия, скачиваем…',current:'Установлена актуальная версия',downloading:'Загрузка обновления',ready:'Обновление готово',error:'Не удалось проверить обновления',development:'Проверка работает в установленной версии'};
if(window.desktop?.onUpdateStatus)window.desktop.onUpdateStatus(({status,detail})=>{const label=updateLabels[status]||'Обновления';$('#updateStatus').textContent=status==='downloading'?`${label}: ${detail}%`:detail&&['available','ready'].includes(status)?`${label} ${detail}`:label;$('#installUpdateBtn').hidden=status!=='ready'});
$('#checkUpdateBtn').addEventListener('click',()=>window.desktop?.checkForUpdates());
$('#installUpdateBtn').addEventListener('click',()=>window.desktop?.installUpdate());

const cropCanvas=$('#cropCanvas'),cropCtx=cropCanvas.getContext('2d');
let cropImage=null,cropRect=null,cropStart=null,cropDataUrl='';
function loadCropFile(file){if(!file||!file.type.startsWith('image/'))return toast('Выберите изображение');const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{cropImage=image;const maxW=1000,maxH=625,scale=Math.min(maxW/image.width,maxH/image.height,1);cropCanvas.width=Math.round(image.width*scale);cropCanvas.height=Math.round(image.height*scale);const pad=.08;cropRect={x:cropCanvas.width*pad,y:cropCanvas.height*pad,w:cropCanvas.width*(1-pad*2),h:cropCanvas.height*(1-pad*2)};$('#cropEmpty').classList.add('hidden');cropCanvas.classList.add('ready');drawCrop();refreshCropOutput()};image.src=reader.result};reader.readAsDataURL(file)}
function drawCrop(){if(!cropImage)return;cropCtx.clearRect(0,0,cropCanvas.width,cropCanvas.height);cropCtx.drawImage(cropImage,0,0,cropCanvas.width,cropCanvas.height);cropCtx.fillStyle='rgba(3,5,9,.58)';cropCtx.fillRect(0,0,cropCanvas.width,cropCanvas.height);cropCtx.save();cropCtx.beginPath();cropCtx.rect(cropRect.x,cropRect.y,cropRect.w,cropRect.h);cropCtx.clip();cropCtx.drawImage(cropImage,0,0,cropCanvas.width,cropCanvas.height);cropCtx.restore();cropCtx.strokeStyle='#a78bfa';cropCtx.lineWidth=3;cropCtx.strokeRect(cropRect.x,cropRect.y,cropRect.w,cropRect.h)}
function canvasPoint(e){const box=cropCanvas.getBoundingClientRect();return{x:(e.clientX-box.left)*cropCanvas.width/box.width,y:(e.clientY-box.top)*cropCanvas.height/box.height}}
cropCanvas.addEventListener('pointerdown',e=>{if(!cropImage)return;cropStart=canvasPoint(e);cropRect={x:cropStart.x,y:cropStart.y,w:1,h:1};cropCanvas.setPointerCapture(e.pointerId)});
cropCanvas.addEventListener('pointermove',e=>{if(!cropStart)return;const p=canvasPoint(e),ratio=+$('#cropRatio').value;let w=p.x-cropStart.x,h=p.y-cropStart.y;if(ratio){const signY=Math.sign(h)||1;h=Math.abs(w)/ratio*signY}cropRect={x:Math.max(0,Math.min(cropStart.x,cropStart.x+w)),y:Math.max(0,Math.min(cropStart.y,cropStart.y+h)),w:Math.min(Math.abs(w),cropCanvas.width-Math.max(0,Math.min(cropStart.x,cropStart.x+w))),h:Math.min(Math.abs(h),cropCanvas.height-Math.max(0,Math.min(cropStart.y,cropStart.y+h)))};drawCrop()});
cropCanvas.addEventListener('pointerup',()=>{cropStart=null;refreshCropOutput()});
function makeCrop(){if(!cropImage||!cropRect||cropRect.w<5||cropRect.h<5)return null;const sourceScale=cropImage.width/cropCanvas.width;const out=document.createElement('canvas'),outW=+$('#cropWidth').value,outH=Math.round(outW*(cropRect.h/cropRect.w));out.width=outW;out.height=outH;out.getContext('2d').drawImage(cropImage,cropRect.x*sourceScale,cropRect.y*sourceScale,cropRect.w*sourceScale,cropRect.h*sourceScale,0,0,outW,outH);const format=$('#cropFormat').value,quality=+$('#cropQuality').value/100;return{data:out.toDataURL(format,quality),format,width:outW,height:outH}}
function refreshCropOutput(){const result=makeCrop();if(!result)return;cropDataUrl=result.data;const bytes=Math.round((result.data.length-result.data.indexOf(',')-1)*.75);$('#cropSize').textContent=`${result.width}×${result.height} • ${bytes>1048576?(bytes/1048576).toFixed(2)+' МБ':Math.round(bytes/1024)+' КБ'}`;$('#saveCrop').disabled=false;$('#useCropAsPhoto').disabled=false}
$('#openCropImage').addEventListener('click',()=>$('#cropFile').click());$('#cropFile').addEventListener('change',e=>loadCropFile(e.target.files[0]));
const cropStage=$('.crop-stage');['dragenter','dragover'].forEach(x=>cropStage.addEventListener(x,e=>{e.preventDefault();cropStage.classList.add('drag')}));['dragleave','drop'].forEach(x=>cropStage.addEventListener(x,e=>{e.preventDefault();cropStage.classList.remove('drag')}));cropStage.addEventListener('drop',e=>loadCropFile(e.dataTransfer.files[0]));
['cropFormat','cropWidth','cropRatio'].forEach(id=>$(`#${id}`).addEventListener('change',refreshCropOutput));$('#cropQuality').addEventListener('input',e=>{$('#qualityValue').textContent=e.target.value+'%';refreshCropOutput()});
$('#saveCrop').addEventListener('click',async()=>{const result=makeCrop();if(!result)return;if(window.desktop){const path=await window.desktop.saveImage({base64:result.data,format:result.format,filename:'majestic-car-'+Date.now()});if(path)toast('Фотография сохранена')}else{const a=document.createElement('a');a.href=result.data;a.download='majestic-car.jpg';a.click()}});
$('#useCropAsPhoto').addEventListener('click',()=>{if(!cropDataUrl)return;openVehicle();$('#photoData').value=cropDataUrl;$('#photoPreview').innerHTML=`<img src="${cropDataUrl}" alt="Фото автомобиля">`;toast('Фото перенесено в карточку')});

setInterval(updateTimers,1000);renderAll();updateTimers();
