const STORAGE_KEY = 'memphis-fleet-desktop-v1';
const now = Date.now();
const SERVERS = ['New York','Detroit','Chicago','San Francisco','Atlanta','San Diego','Los Angeles','Miami','Las Vegas','Washington','Dallas','Boston','Houston','Seattle','Phoenix','Denver','Portland','Orlando','Memphis'];
const blankProfile = (id='profile-1',name='Персонаж 1',server='Memphis') => ({id,name,server,cash:0,vehicles:[],assets:[],rentals:[],rentalHistory:[],deals:[],resellerItems:[],resellerHistory:[],workIncomes:[]});
const seed = {activeServer:'Memphis',activeProfileId:'profile-1',profiles:[blankProfile()]};
let database = load();
let state = getActiveProfile();
let currentFilter = 'all';
let catalogCategory = 'all';
let catalogPage = 1;
const CATALOG_PAGE_SIZE = 24;
const categorySets = Object.fromEntries(Object.entries(window.VEHICLE_CATEGORIES||{}).map(([key,ids])=>[key,new Set(ids)]));

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const THEME_KEY='fleet-desk-theme',systemTheme=matchMedia('(prefers-color-scheme: light)');
function applyTheme(choice=localStorage.getItem(THEME_KEY)||'system'){const resolved=choice==='system'?(systemTheme.matches?'light':'dark'):choice;document.documentElement.dataset.theme=resolved;document.documentElement.style.colorScheme=resolved;const select=$('#themeSelect');if(select)select.value=choice}
applyTheme();
const money = n => '$' + Math.round(Number(n)||0).toLocaleString('ru-RU');
const mc = n => Math.round(Number(n)||0).toLocaleString('ru-RU') + ' MC';
const purchaseMoney = v => v?.purchaseCurrency==='mc'?mc(v.purchase):money(v?.purchase);
const dealMoney = d => d?.currency==='mc'?mc(d.amount):money(d?.amount);
const vehicleValue = v => +v.govPrice||+v.market||(v.purchaseCurrency==='mc'?0:+v.purchase||0);
const parseMoney = value => Number(String(value??'').replace(/[^\d]/g,''))||0;
const inputMoney = value => value===''||value==null?'':Math.round(Number(value)||0).toLocaleString('ru-RU');
const uid = p => p + Date.now().toString(36) + Math.random().toString(36).slice(2,7);
const statusName = s => ({available:'Свободна',rented:'В аренде',sale:'На продаже',personal:'Личная'}[s]||s);
const assetTypes={house:{name:'Дом',icon:'⌂'},apartment:{name:'Квартира',icon:'▤'},yacht:{name:'Яхта',icon:'⚓'},business:{name:'Бизнес',icon:'◆'},atm:{name:'Банкомат',icon:'▣'},office:{name:'Офис',icon:'▥'},warehouse:{name:'Склад',icon:'▦'},other:{name:'Другое',icon:'◇'}};
const vehicle = id => state.vehicles.find(v=>v.id===id);
const esc = value => String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));

function normalizeVehicle(v){const catalogItem=(window.VEHICLE_CATALOG||[]).find(x=>x.id===v?.catalogId)||(window.VEHICLE_CATALOG||[]).find(x=>x.name===v?.name);const catalogId=v?.catalogId||catalogItem?.id||'';const prices=(window.VEHICLE_PRICES||{})[catalogId]||{};const purchaseCurrency=v?.purchaseCurrency==='mc'?'mc':'money';const legacyRunnerGov={msprinter:32000000,dsprinter:28000000}[catalogId],storedGov=+v?.govPrice||0,govPrice=legacyRunnerGov===storedGov?(+prices.govPrice||0):(storedGov||+prices.govPrice||0);const legacyRunnerScrap={msprinter:16000000,dsprinter:14000000}[catalogId],storedScrap=+v?.scrap||0,correctedScrap=legacyRunnerScrap===storedScrap?Math.round(govPrice*.5):storedScrap;const scrap=purchaseCurrency==='mc'?(correctedScrap||+prices.mcScrapPrice||Math.round(govPrice*.5)):(correctedScrap||Math.round(govPrice*.5));return{purchaseCurrency,govPrice,catalogId,scrap,...v,purchaseCurrency,govPrice,catalogId,scrap}}
function normalizeDatabase(saved){if(saved?.profiles?.length){const profiles=saved.profiles.map(p=>{const profile={...blankProfile(p.id,p.name,p.server||'Memphis'),...p,server:p.server||'Memphis'};profile.vehicles=(profile.vehicles||[]).map(normalizeVehicle);return profile});const selected=profiles.find(p=>p.id===saved.activeProfileId);const activeServer=saved.activeServer||selected?.server||'Memphis';let activeProfileId=selected?.server===activeServer?selected.id:profiles.find(p=>p.server===activeServer)?.id;if(!activeProfileId){const profile=blankProfile(uid('p'),'Персонаж 1',activeServer);profiles.push(profile);activeProfileId=profile.id}return{...saved,activeServer,activeProfileId,profiles}}const legacy={...blankProfile(),...(saved||{})};legacy.id='profile-1';legacy.name='Персонаж 1';legacy.server='Memphis';legacy.vehicles=(legacy.vehicles||[]).map(v=>normalizeVehicle({...v,advert:['vrs6','vlc'].includes(v.id)?'':(v.advert||'')}));return{activeServer:'Memphis',activeProfileId:legacy.id,profiles:[legacy]}}
function load(){try{return normalizeDatabase(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return structuredClone(seed)}}
function getActiveProfile(){return database.profiles.find(p=>p.id===database.activeProfileId&&p.server===database.activeServer)||database.profiles.find(p=>p.server===database.activeServer)||database.profiles[0]}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(database));renderAll()}
function img(v,cls=''){return v?.photo?`<img class="${cls}" src="${v.photo}" alt="${v.name}">`:`<div class="car-placeholder ${cls}">${(v?.name||'AUTO').split(' ').slice(-1)[0].slice(0,3).toUpperCase()}</div>`}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}

function renderAll(){
  const fleetValue=state.vehicles.reduce((s,v)=>s+vehicleValue(v),0);
  const assetValue=(state.assets||[]).reduce((s,item)=>s+(+item.value||0),0);
  const taxable=(state.assets||[]).filter(item=>+item.taxPerDay>0),nearest=taxable.slice().sort((a,b)=>(+a.paidUntil||0)-(+b.paidUntil||0))[0],nearestDays=nearest?Math.max(0,Math.ceil(((+nearest.paidUntil||0)-Date.now())/864e5)):0,dailyTax=taxable.reduce((sum,item)=>sum+(+item.taxPerDay||0),0);
  $('#headerCash').textContent=money(state.cash);
  $('#serverSelect').innerHTML=SERVERS.map(server=>`<option value="${server}" ${server===database.activeServer?'selected':''}>${server}</option>`).join('');
  $('#profileSelect').innerHTML=database.profiles.filter(p=>p.server===database.activeServer).map(p=>`<option value="${p.id}" ${p.id===database.activeProfileId?'selected':''}>${esc(p.name)}</option>`).join('');
  $('#stats').innerHTML=[
    ['Стоимость всего имущества',money(fleetValue+assetValue),`${state.vehicles.length} авто · ${(state.assets||[]).length} объектов`,'rgba(223,44,172,.14)'],
    ['Свободный баланс',money(state.cash),'Доступно для покупок и налогов','rgba(47,212,167,.14)'],
    ['Налоги и содержание',money(dailyTax)+' / день',nearest?`${esc(nearest.name)}: осталось ${nearestDays} дн.`:'Нет объектов с налогом','rgba(255,189,89,.14)']
  ].map(x=>`<div class="stat" style="--glow:${x[3]}"><span class="stat-label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
  renderGarage();renderRentals();renderDeals();renderDashboard();renderReseller();fillVehicleSelects();
}

function renderDashboard(){
  const deals=[...state.deals].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  $('#recentActivity').innerHTML=deals.map(d=>`<div class="activity"><small>${d.date}</small><span>${dealType(d.type)}</span><b>${vehicle(d.vehicleId)?.name||d.vehicleName||'Без автомобиля'}</b><strong class="amount ${['income','sale','scrapSale'].includes(d.type)?'positive':'negative'}">${['income','sale','scrapSale'].includes(d.type)?'+':'−'}${dealMoney(d)}</strong></div>`).join('')||'<div class="empty">Операций пока нет</div>';
  renderAssets();
}

let assetEditMode=false;
function assetLevel(item,key){return +item?.upgradeLevels?.[key]||0}
function assetLevelRow(label,level){return `<span><small>${label}</small><b>${level?`${level} ур.`:'Базовый'}</b></span>`}
function assetSummary(item){const catalog=findAssetCatalogItem(item.type,item.catalogId,item.name),levels=item.upgradeLevels||legacyUpgradeLevels(item.upgrades),rows=[];if(item.type==='house'){const base=assetGaragePlaces(catalog),places=base+(+levels.garage||0)*2;rows.push(`<span><small>ГАРАЖНЫХ МЕСТ</small><b>${places||'—'}</b></span>`,assetLevelRow('КУХНЯ',levels.kitchen),assetLevelRow('КЛАДОВКА',levels.storage),assetLevelRow('МАСТЕРСКАЯ',levels.workshop))}else if(item.type==='apartment')rows.push(assetLevelRow('КУХНЯ',levels.kitchen),assetLevelRow('КЛАДОВКА',levels.storage));else if(item.type==='yacht')rows.push(assetLevelRow('КУХНЯ',levels.kitchen),assetLevelRow('СКЛАД',levels.yachtStorage),assetLevelRow('МАРИНА',levels.marina));return rows.length?`<div class="property-details">${rows.join('')}</div>`:''}
function renderAssets(){
  state.assets??=[];
  const priority={house:1,apartment:2,business:3,atm:4,yacht:5,office:6,warehouse:7,other:8};
  const items=state.assets.slice().sort((a,b)=>(priority[a.type]||9)-(priority[b.type]||9));
  $('#assetGrid').className=`property-grid ${assetEditMode?'is-editing':''}`;
  const garageValue=state.vehicles.reduce((sum,item)=>sum+vehicleValue(item),0);
  const garage=`<button type="button" class="property-card property-garage" data-jump="garage"><div class="property-card-top"><span class="property-icon">▦</span><span class="property-open">Открыть →</span></div><div><small>ГАРАЖ</small><h3>${state.vehicles.length} ${state.vehicles.length===1?'автомобиль':'автомобилей'}</h3></div><div class="property-garage-value"><small>СТОИМОСТЬ АВТОПАРКА</small><b>${money(garageValue)}</b></div></button>`;
  const cards=items.map(item=>{const type=assetTypes[item.type]||assetTypes.other,remaining=(+item.paidUntil||0)-Date.now(),days=Math.max(0,Math.ceil(remaining/864e5)),urgent=remaining<=7*864e5;return`<article class="property-card property-${item.type} ${urgent?'tax-urgent':''}" data-property-id="${item.id}"><div class="property-edit-actions"><button data-edit-asset="${item.id}" title="Изменить">✎</button><button class="danger" data-dispose-asset="${item.id}" title="Продать или обменять">×</button></div><div class="property-card-top"><span class="property-icon">${type.icon}</span><span class="property-tax"><small>НАЛОГ / СУТКИ</small><b>${item.taxPerDay?money(item.taxPerDay):'—'}</b></span></div><div><small>${type.name.toUpperCase()}</small><h3>${esc(item.name)}</h3></div>${assetSummary(item)}<div class="property-card-bottom"><span><small>ОПЛАЧЕНО</small><b class="${urgent?'negative':''}">${item.paidUntil?(remaining>0?`${days} дн.`:'Просрочено'):'Не указано'}</b></span><button class="property-tax-button" data-pay-tax="${item.id}" ${item.taxPerDay?'':'disabled'}>Оплатить</button></div></article>`}).join('');
  $('#assetGrid').innerHTML=garage+cards;
}

const assetCatalogConfig={house:{kind:'homes',label:'Дом',placeholder:'Выберите дом',match:item=>!/квартир/i.test(item.name||'')},apartment:{kind:'homes',label:'Квартира',placeholder:'Выберите квартиру',match:item=>/квартир/i.test(item.name||'')},yacht:{label:'Яхта',placeholder:'Выберите яхту',staticItems:[{id:'yacht',name:'Яхта'}],match:()=>true},business:{kind:'businesses',label:'Бизнес',placeholder:'Выберите бизнес',match:()=>true},atm:{kind:'atms',label:'Банкомат',placeholder:'Выберите банкомат',match:()=>true},office:{kind:'offices',label:'Офис',placeholder:'Выберите офис',match:item=>!/склад/i.test(item.name||'')},warehouse:{kind:'offices',label:'Склад',placeholder:'Выберите склад',match:item=>/склад/i.test(item.name||'')}};
const assetCatalogItems=config=>config.staticItems||localCatalogItems(config.kind);
const assetUpgradeDefinitions={garage:{name:'Гараж',icon:'▣',types:['house'],maxLevel:3},kitchen:{name:'Кухня',icon:'♨',types:['house','apartment','yacht'],maxLevel:5},storage:{name:'Кладовка',icon:'▤',types:['house','apartment'],maxLevel:5},workshop:{name:'Мастерская',icon:'⚒',types:['house'],maxLevel:3},yachtStorage:{name:'Склад',icon:'▤',types:['yacht'],maxLevel:5},marina:{name:'Марина',icon:'<img src="assets/marina.svg" alt="">',types:['yacht'],maxLevel:2}};
let assetCatalogRequest=0;
function renderAssetNameOptions(selectedName='',selectedCatalogId=''){const form=$('#assetForm'),type=form.elements.namedItem('type').value,config=assetCatalogConfig[type]||assetCatalogConfig.house,select=form.elements.namedItem('name'),query=$('#assetNameSearch').value.trim().toLocaleLowerCase('ru-RU'),garageFilter=$('#assetGarageFilter').value,allItems=assetCatalogItems(config).filter(config.match),items=allItems.filter(item=>(!query||`${item.name} ${item.id}`.toLocaleLowerCase('ru-RU').includes(query))&&(type!=='house'||garageFilter==='all'||assetGaragePlaces(item)===+garageFilter)).sort((a,b)=>(a.name||'').localeCompare(b.name||'','ru'));$('#assetNameLabel').textContent=config.label;$('#assetGarageFilter').hidden=type!=='house';$('#assetNameSearch').placeholder=type==='house'?'Поиск по номеру дома':`Поиск: ${config.label.toLowerCase()}`;select.innerHTML=`<option value="">${items.length?config.placeholder:'Ничего не найдено'}</option>`+items.map(item=>`<option value="${esc(item.name)}" data-catalog-id="${esc(item.id)}">${esc(item.name)}${type==='house'&&assetGaragePlaces(item)?` · ${assetGaragePlaces(item)} г.м.`:''}</option>`).join('');if(selectedName&&!allItems.some(item=>item.name===selectedName))select.insertAdjacentHTML('beforeend',`<option value="${esc(selectedName)}" data-catalog-id="${esc(selectedCatalogId)}">${esc(selectedName)} · сохранено ранее</option>`);select.value=selectedName||'';form.elements.namedItem('catalogId').value=select.selectedOptions[0]?.dataset.catalogId||selectedCatalogId||'';return allItems.length}
function syncAssetNameOptions(selectedName='',selectedCatalogId=''){const request=++assetCatalogRequest,form=$('#assetForm'),type=form.elements.namedItem('type').value,config=assetCatalogConfig[type]||assetCatalogConfig.house,hasItems=renderAssetNameOptions(selectedName,selectedCatalogId);if(!hasItems){const select=form.elements.namedItem('name');select.innerHTML='<option value="">Каталог загружается…</option>';select.disabled=true}Promise.resolve(config.kind?warmLocalCatalog(config.kind):null).finally(()=>{if(request!==assetCatalogRequest)return;form.elements.namedItem('name').disabled=false;renderAssetNameOptions(selectedName,selectedCatalogId);renderAssetUpgradePicker(type,readAssetUpgradeLevels(),findAssetCatalogItem(type,selectedCatalogId,selectedName))})}
function legacyUpgradeLevels(text=''){const levels={};for(const [key,definition] of Object.entries(assetUpgradeDefinitions)){const match=String(text).match(new RegExp(`${definition.name}[^0-9]*(\\d+)`,'i'));if(match)levels[key]=Math.max(0,Math.min(3,+match[1]||0))}return levels}
function findAssetCatalogItem(type,catalogId='',name=''){const config=assetCatalogConfig[type]||assetCatalogConfig.house;return assetCatalogItems(config).find(item=>(catalogId&&String(item.id)===String(catalogId))||(!catalogId&&name&&item.name===name))||null}
function assetGaragePlaces(item){const field=(item?.fields||[]).find(entry=>/гаражных мест/i.test(entry.label||''));return Number(String(field?.value||'').match(/\d+/)?.[0])||0}
function renderAssetUpgradePicker(type,levels={},catalogItem=null){const available=Object.entries(assetUpgradeDefinitions).filter(([,definition])=>definition.types.includes(type)),garagePlaces=type==='house'?assetGaragePlaces(catalogItem):0;$('#assetUpgradePicker').hidden=!available.length;$('#assetUpgradeGrid').innerHTML=available.map(([key,definition])=>{const maxLevel=key==='garage'?(garagePlaces===30?0:garagePlaces===10?4:definition.maxLevel):definition.maxLevel,level=Math.min(+levels[key]||0,maxLevel),levelOptions=Array.from({length:maxLevel},(_,index)=>index+1),baseHint=key==='garage'&&garagePlaces?(maxLevel?`Базово ${garagePlaces} мест · до ${maxLevel} ур.`:`Базово ${garagePlaces} мест · без улучшений`):'',locked=key==='garage'&&garagePlaces===30;return`<div class="asset-upgrade-option ${level?'active':''} ${locked?'locked':''}" data-asset-upgrade-card><span class="asset-upgrade-icon">${definition.icon}</span><div><b>${definition.name}</b>${baseHint?`<small>${baseHint}</small>`:''}<select name="upgrade_${key}" ${locked?'disabled':''}><option value="0">${locked?'Базовый уровень':'Без улучшения'}</option>${levelOptions.map(value=>`<option value="${value}" ${level===value?'selected':''}>${value} уровень</option>`).join('')}</select></div></div>`}).join('')}
function readAssetUpgradeLevels(){const levels={};for(const key of Object.keys(assetUpgradeDefinitions)){const select=$(`#assetUpgradeGrid [name="upgrade_${key}"]`);if(select&&+select.value)levels[key]=+select.value}return levels}
function assetUpgradeText(levels={}){return Object.entries(levels).filter(([,level])=>+level>0).map(([key,level])=>`${assetUpgradeDefinitions[key]?.name||key} — ${level} ур.`).join(' · ')}
function openAsset(item=null,presetType='house'){const form=$('#assetForm');form.reset();form.elements.namedItem('editId').value=item?.id||'';form.elements.namedItem('type').value=assetCatalogConfig[item?.type]?item.type:presetType;form.elements.namedItem('value').value=inputMoney(item?.value);form.elements.namedItem('taxPerDay').value=inputMoney(item?.taxPerDay);form.elements.namedItem('paidUntil').value=item?.paidUntil?new Date(item.paidUntil).toISOString().slice(0,10):'';$('#assetNameSearch').value='';$('#assetGarageFilter').value='all';syncAssetNameOptions(item?.name||'',item?.catalogId||'');renderAssetUpgradePicker(form.elements.namedItem('type').value,item?.upgradeLevels||legacyUpgradeLevels(item?.upgrades),findAssetCatalogItem(form.elements.namedItem('type').value,item?.catalogId,item?.name));$('#assetDialogTitle').textContent=item?'Изменить имущество':`Добавить: ${assetTypes[presetType]?.name||'имущество'}`;$('#assetDialog').showModal();requestAnimationFrame(()=>$('#assetNameSearch').focus())}
function openTaxPayment(item){if(!item?.taxPerDay)return toast('Сначала укажите налог за сутки');const form=$('#taxForm');form.reset();form.elements.namedItem('assetId').value=item.id;form.elements.namedItem('days').value=1;$('#taxDialogTitle').textContent=`Оплатить: ${item.name}`;$('#taxDialog').showModal();renderTaxPaymentPreview()}
function renderTaxPaymentPreview(){const form=$('#taxForm'),item=(state.assets||[]).find(asset=>asset.id===form.elements.namedItem('assetId').value),days=Math.max(1,+form.elements.namedItem('days').value||1);if(!item)return;const currentDays=Math.max(0,Math.ceil(((+item.paidUntil||0)-Date.now())/864e5)),allowed=Math.max(0,30-currentDays),actual=Math.min(days,allowed);$('#taxPaymentPreview').innerHTML=`<span>Сейчас оплачено: <b>${currentDays} дн.</b></span><span>К оплате: <b>${actual} дн. · ${money(actual*item.taxPerDay)}</b></span>`}
function openAssetDisposal(item){if(!item)return;const form=$('#assetDisposeForm');form.reset();form.elements.namedItem('assetId').value=item.id;$('#assetDisposeTitle').textContent=item.name;syncAssetDisposal();$('#assetDisposeDialog').showModal()}
function syncAssetDisposal(){const exchange=$('#assetDisposeForm').elements.namedItem('operation').value==='exchange';$('#assetDisposeAmountLabel').hidden=exchange;$('#assetDisposeHint').textContent=exchange?'Старый объект и его налоговый таймер будут закрыты, затем откроется форма нового имущества.':'Сумма поступит на свободный баланс и будет записана в операции.'}
function checkAssetTaxNotifications(){state.taxNotices??={};let changed=false;for(const item of state.assets||[]){if(!item.taxPerDay||!item.paidUntil)continue;const remaining=item.paidUntil-Date.now();let key='',message='';if(remaining<=0){key='overdue';message='Расчётный срок оплаты истёк'}else if(remaining<=12*36e5){key='12h';message='По расчёту до окончания оплаты меньше 12 часов'}else{const days=Math.ceil(remaining/864e5);if(days>7)continue;key=days+'d';message=`По расчёту оплачено ещё на ${days} дн.`}const noticeKey=`${item.id}:${item.paidUntil}:${key}`;if(state.taxNotices[noticeKey])continue;state.taxNotices[noticeKey]=Date.now();changed=true;window.desktop?.showNotification?.({title:`Налог: ${item.name}`,body:`${message}. Налог ${money(item.taxPerDay)} в сутки.`})}if(changed)localStorage.setItem(STORAGE_KEY,JSON.stringify(database))}

function renderGarage(){
  const q=$('#garageSearch')?.value?.toLowerCase()||'';
  const list=state.vehicles.filter(v=>(currentFilter==='all'||v.status===currentFilter)&&(`${v.name} ${v.plate}`.toLowerCase().includes(q)));
  $('#garageGrid').innerHTML=list.map(v=>`<article class="car-card"><span class="status ${v.status}">${statusName(v.status)}</span>${v.purchaseCurrency==='mc'?'<span class="mc-badge">MC</span>':''}${img(v)}<div class="car-body"><div class="car-title"><div><b>${esc(v.name)}</b><small>${esc(v.plate||'Без номера')}</small></div><span class="car-value">${v.govPrice?money(v.govPrice):'Госцена не указана'}</span></div><div class="car-metrics"><div class="metric"><small>ПОКУПКА</small><b>${purchaseMoney(v)}</b></div><div class="metric"><small>ГОС. ЦЕНА</small><b>${v.govPrice?money(v.govPrice):'—'}</b></div><div class="metric"><small>СВАЛКА</small><b>${money(v.scrap)}</b></div></div><div class="card-ad-editor"><label for="ad-${v.id}">ТЕКСТ ОБЪЯВЛЕНИЯ</label><textarea id="ad-${v.id}" data-ad-input="${v.id}" rows="3" placeholder="Введите текст объявления">${esc(v.advert)}</textarea><div><button data-save-ad="${v.id}">Сохранить текст</button><button class="copy-action" data-copy-ad="${v.id}" ${v.advert?'':'disabled'}>Копировать</button></div></div><div class="card-actions"><button data-rent="${v.id}" ${v.status==='rented'?'disabled':''}>В аренду</button><button data-edit-car="${v.id}">Изменить</button><button class="danger" data-delete-car="${v.id}">Удалить</button></div></div></article>`).join('')||'<div class="empty">Ничего не найдено</div>';
}

function rentalMini(r){const v=vehicle(r.vehicleId);const pct=Math.max(0,Math.min(100,(r.end-Date.now())/(r.end-r.start)*100));return `<div class="rental-mini"><div class="row-between"><div><b>${v?.name||'Транспорт'}</b><small> • ${money(r.price)} / ${r.unit==='day'?'сутки':'час'}</small></div><span class="timer" data-end="${r.end}"></span></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
function renderRentals(){
  $('#rentalList').innerHTML=state.rentals.map(r=>{const v=vehicle(r.vehicleId);return `<article class="rental-card">${img(v,'rent-thumb')}<div><h3>${v?.name||'Транспорт'}</h3><p>${money(r.price)} / ${r.unit==='day'?'сутки':'час'} • ${r.duration||Math.round(r.hours/(r.unit==='day'?24:1))} ${r.unit==='day'?'сут.':'ч.'}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,(r.end-Date.now())/(r.end-r.start)*100))}%"></i></div></div><div class="rental-actions"><span class="timer" data-end="${r.end}"></span><button data-extend="${r.id}">+24 часа</button><button data-return="${r.id}">Возвращена</button></div></article>`}).join('')||'<div class="empty">Активной аренды нет</div>';
  $('#rentalHistory').innerHTML=state.rentalHistory.slice().reverse().slice(0,12).map(r=>`<div class="history-item"><div class="row-between"><b>${r.vehicleName}</b><strong class="amount positive">+${money(r.total||r.price)}</strong></div><small>${new Date(r.returned).toLocaleString('ru-RU')}</small></div>`).join('')||'<div class="empty">История пока пустая</div>';
}

function dealType(t){return({income:'Доход',expense:'Расход',purchase:'Покупка',sale:'Продажа игроку',scrapSale:'Продажа на свалку'}[t]||t)}
function renderDeals(){
  const dollarDeals=state.deals.filter(d=>d.currency!=='mc');
  const inc=dollarDeals.filter(d=>['income','sale','scrapSale'].includes(d.type)).reduce((s,d)=>s+(+d.amount||0),0);
  const out=dollarDeals.filter(d=>['expense','purchase'].includes(d.type)).reduce((s,d)=>s+(+d.amount||0),0);
  $('#dealSummary').innerHTML=`<div class="deal-chip"><small>Доходы</small><b class="amount positive">${money(inc)}</b></div><div class="deal-chip"><small>Расходы</small><b class="amount negative">${money(out)}</b></div><div class="deal-chip"><small>Результат</small><b>${money(inc-out)}</b></div>`;
  $('#dealTable').innerHTML=state.deals.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(d=>`<tr><td>${d.date}</td><td>${dealType(d.type)}</td><td>${vehicle(d.vehicleId)?.name||d.vehicleName||'—'}</td><td>${d.note||'—'}</td><td class="amount ${['income','sale','scrapSale'].includes(d.type)?'positive':'negative'}">${['income','sale','scrapSale'].includes(d.type)?'+':'−'}${dealMoney(d)}</td><td><button class="icon-btn danger" data-delete-deal="${d.id}">×</button></td></tr>`).join('');
}

const resellerMarketplaceFee=gross=>Math.min(Math.round((+gross||0)*.03),250000);
const resellerSaleNet=sale=>{const gross=(+sale.qty||0)*(+sale.unit||0);return sale.channel==='marketplace'?gross-resellerMarketplaceFee(gross):gross};
function resellerTotals(item){const invested=item.buyCost==null?(+item.buyQty||0)*(+item.buyUnit||0):(+item.buyCost||0),sold=(item.sales||[]).reduce((s,x)=>s+(+x.qty||0),0),received=(item.sales||[]).reduce((s,x)=>s+resellerSaleNet(x),0);return{invested,sold,received,remaining:Math.max(0,(+item.buyQty||0)-sold),result:received-invested}}
function resellerResultText(value){return(value<0?'−':'')+money(Math.abs(value))}
function resellerDayKey(value){const date=new Date(value);return Number.isNaN(date.getTime())?'':`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function archiveResellerItem(item,closedAt=Date.now()){const totals=resellerTotals(item);state.resellerHistory??=[];state.resellerHistory.unshift({...item,closedAt,totals});state.resellerItems=(state.resellerItems||[]).filter(x=>x.id!==item.id)}
function resellerDailyRows(){const rows=new Map(),all=[...(state.resellerItems||[]),...(state.resellerHistory||[])];for(const item of all){for(const sale of item.sales||[]){const day=resellerDayKey(sale.at);if(!day)continue;const result=resellerSaleNet(sale)-(+sale.qty||0)*(+item.buyUnit||0),row=rows.get(day)||{day,result:0,sales:0,jobs:0};row.result+=result;row.sales++;rows.set(day,row)}}for(const income of state.workIncomes||[]){const day=resellerDayKey(income.at||income.date);if(!day)continue;const row=rows.get(day)||{day,result:0,sales:0,jobs:0};row.result+=+income.amount||0;row.jobs++;rows.set(day,row)}return[...rows.values()].sort((a,b)=>b.day.localeCompare(a.day))}
function resellerHistoryRow(item){const t=resellerTotals(item);return`<article class="reseller-history-row">${item.image?`<img src="${esc(item.image)}" alt="">`:'<span class="reseller-placeholder">◈</span>'}<div><small>${esc(item.category||'Имущество')}</small><b>${esc(item.name)}</b><span>${item.closedAt?new Date(item.closedAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):'Время не сохранено'} · ${t.sold} шт.</span></div><strong class="${t.result>=0?'positive':'negative'}">${resellerResultText(t.result)}</strong></article>`}
function renderResellerReports(){const history=state.resellerHistory||[],today=resellerDayKey(Date.now()),todayItems=history.filter(item=>resellerDayKey(item.closedAt)===today),groups=new Map();for(const item of history){const day=resellerDayKey(item.closedAt)||'unknown';if(day===today)continue;if(!groups.has(day))groups.set(day,[]);groups.get(day).push(item)}$('#resellerTodayDate').textContent=new Date().toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'});$('#resellerTodayClosed').innerHTML=todayItems.map(resellerHistoryRow).join('')||'<div class="empty">Сегодня закрытых позиций пока нет</div>';$('#resellerHistoryList').innerHTML=[...groups].sort((a,b)=>b[0].localeCompare(a[0])).map(([day,items])=>{const result=items.reduce((sum,item)=>sum+resellerTotals(item).result,0);return`<details class="reseller-history-day"><summary><div><b>${day==='unknown'?'Без даты':new Date(day+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</b><small>${items.length} ${items.length===1?'позиция':'позиций'}</small></div><strong class="${result>=0?'positive':'negative'}">${resellerResultText(result)}</strong></summary><div class="reseller-history-day-items">${items.map(resellerHistoryRow).join('')}</div></details>`}).join('')||'<div class="empty">Прошедших дневных отчётов пока нет</div>';const days=resellerDailyRows();$('#resellerDailyList').innerHTML=days.map(row=>`<div class="reseller-day-row"><div><b>${new Date(row.day+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})}</b><small>${row.sales} продаж · ${row.jobs} доходов с работ</small></div><strong class="${row.result>=0?'positive':'negative'}">${resellerResultText(row.result)}</strong></div>`).join('')||'<div class="empty">Дневная статистика появится после продаж или работы</div>'}
function renderReseller(){state.resellerItems??=[];state.resellerHistory??=[];state.workIncomes??=[];const stale=state.resellerItems.filter(x=>(x.sales||[]).length&&resellerTotals(x).remaining===0);for(const item of stale)archiveResellerItem(item,null);if(stale.length)persistReseller();const items=state.resellerItems,history=state.resellerHistory,all=[...items,...history],totals=all.reduce((a,x)=>{const t=x.totals||resellerTotals(x);a.invested+=t.invested;a.received+=t.received;a.result+=t.result;return a},{invested:0,received:0,result:0}),workTotal=state.workIncomes.reduce((sum,x)=>sum+(+x.amount||0),0),qty=items.reduce((sum,x)=>sum+resellerTotals(x).remaining,0),today=resellerDailyRows().find(x=>x.day===resellerDayKey(Date.now()))?.result||0;totals.received+=workTotal;totals.result+=workTotal;$('#resellerUndoBtn').disabled=!state.resellerUndo;$('#resellerUndoBtn').title=state.resellerUndo?`Отменить: ${state.resellerUndo.label}`:'Нет действия для отмены';$('#resellerSummary').innerHTML=[['Активных позиций',items.length],['Имущества в наличии',qty],['Вложено за всё время',money(totals.invested)],['Получено за всё время',money(totals.received)],['Общий результат',resellerResultText(totals.result)],['Прибыль сегодня',resellerResultText(today)]].map((x,i)=>`<div class="reseller-stat"><small>${x[0]}</small><b class="${i>=4?(Number(i===4?totals.result:today)>=0?'positive':'negative'):''}">${x[1]}</b></div>`).join('');$('#resellerList').innerHTML=items.map(item=>{const t=resellerTotals(item),bought=+item.buyQty||0;return `<article class="reseller-card reseller-card-compact" data-reseller-card="${item.id}"><div class="reseller-head">${item.image?`<img src="${esc(item.image)}" alt="">`:'<span class="reseller-placeholder">◈</span>'}<div><small>${esc(item.category||'Имущество')}</small><h3>${esc(item.name)}</h3></div><button class="icon-btn danger" data-reseller-delete="${item.id}" title="Удалить позицию">×</button></div><div class="reseller-metrics"><div><small>Куплено</small><b>${bought} шт.</b></div><div><small>Продано</small><b>${t.sold} шт.</b></div><div><small>В наличии</small><b>${t.remaining} шт.</b></div><div><small>Вложено</small><b>${money(t.invested)}</b></div><div><small>Получено</small><b>${money(t.received)}</b></div><div><small>Результат</small><b class="${t.result>=0?'positive':'negative'}">${resellerResultText(t.result)}</b></div></div><div class="reseller-card-actions"><button class="ghost" data-reseller-buy="${item.id}">+ Купить</button><button class="primary" data-reseller-sell="${item.id}">Продать</button></div></article>`}).join('')||'<div class="empty">Активных позиций нет — закрытые сделки находятся в истории</div>';renderResellerReports()}
function persistReseller(){localStorage.setItem(STORAGE_KEY,JSON.stringify(database))}
function rememberResellerAction(label){state.resellerUndo={label,items:structuredClone(state.resellerItems||[]),history:structuredClone(state.resellerHistory||[]),workIncomes:structuredClone(state.workIncomes||[])}}
function undoResellerAction(){const snapshot=state.resellerUndo;if(!snapshot)return;state.resellerItems=snapshot.items;state.resellerHistory=snapshot.history;state.workIncomes=snapshot.workIncomes;delete state.resellerUndo;persistReseller();renderReseller();toast(`Отменено: ${snapshot.label}`)}
function addToReseller(source){state.resellerItems??=[];const existing=state.resellerItems.find(x=>x.sourceType===source.sourceType&&x.sourceId===source.sourceId);if(existing){toast('Эта позиция уже есть в калькуляторе');return}state.resellerItems.push({id:uid('r'),sourceType:source.sourceType,sourceId:source.sourceId,name:source.name,image:source.image||'',category:source.category||'',buyQty:0,buyUnit:0,sales:[]});persistReseller();renderReseller();toast('Добавлено в калькулятор прибыли')}

function fillVehicleSelects(){
  $('#dealVehicle').innerHTML='<option value="">Без автомобиля</option>'+state.vehicles.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');
  $('#rentalCarPicker').innerHTML=state.vehicles.filter(v=>v.status!=='rented').map(v=>`<button type="button" class="pick-car" data-pick="${v.id}">${img(v)}<b>${v.name}</b></button>`).join('')||'<div class="empty">Нет свободных машин</div>';
}

function updateTimers(){
  $$('[data-end]').forEach(el=>{const ms=+el.dataset.end-Date.now();if(ms<=0){el.textContent='Просрочено';el.style.color='var(--red)';return}const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1000);el.textContent=`${h}ч ${String(m).padStart(2,'0')}м ${String(s).padStart(2,'0')}с`});
}

function openRental(id){fillVehicleSelects();const form=$('#rentalForm');form.reset();form.elements.namedItem('vehicleId').value=id||'';setRentalUnit('hour');$$('.pick-car').forEach(b=>b.classList.toggle('selected',b.dataset.pick===id));syncRentalAd();$('#rentalDialog').showModal()}
function syncRentalAd(){const id=$('#rentalForm').elements.namedItem('vehicleId').value;const v=vehicle(id);$('#rentalAdBox span').textContent=v?.advert||'У выбранной машины пока нет шаблона';$('#copyRentalAd').disabled=!v?.advert}
async function copyAdvert(id){const text=vehicle(id)?.advert;if(!text)return toast('Сначала добавьте текст объявления');try{await navigator.clipboard.writeText(text);toast('Объявление скопировано')}catch{toast('Не удалось скопировать текст')}}
function catalogPrices(id){return (window.VEHICLE_PRICES||{})[id]||{}}
function syncVehiclePrices({preserveMcScrap=false}={}){const f=$('#vehicleForm'),field=name=>f.elements.namedItem(name),currency=field('purchaseCurrency').value,prices=catalogPrices(field('catalogId').value),gov=+prices.govPrice||parseMoney(field('govPrice').value);field('govPrice').value=inputMoney(gov);field('govPrice').readOnly=true;if(currency==='money'){field('scrap').value=inputMoney(Math.round(gov*.5));field('scrap').readOnly=true;field('scrap').placeholder='50% государственной цены';field('scrap').title='Для обычной техники цена свалки рассчитывается как 50% государственной цены'}else{const suggestedScrap=+prices.mcScrapPrice||+prices.scrapPrice||0;if(prices.mcPrice&&!parseMoney(field('purchase').value))field('purchase').value=inputMoney(prices.mcPrice);if(suggestedScrap&&!preserveMcScrap&&!parseMoney(field('scrap').value))field('scrap').value=inputMoney(suggestedScrap);else if(!suggestedScrap&&!preserveMcScrap)field('scrap').value='';field('scrap').readOnly=false;field('scrap').placeholder='Введите фактическую цену свалки';field('scrap').title='У MC-техники цена свалки может отличаться — поле можно исправить вручную'}}
function setPurchaseCurrency(currency,{preserveMcScrap=false}={}){const f=$('#vehicleForm');f.elements.namedItem('purchaseCurrency').value=currency;$$('[data-purchase-currency]').forEach(b=>b.classList.toggle('active',b.dataset.purchaseCurrency===currency));$('#purchasePriceLabel').childNodes[0].nodeValue=currency==='mc'?'Цена покупки, MC':'Цена покупки, $';$('#mcPurchaseHint').hidden=currency!=='mc';if(currency==='mc'&&f.elements.namedItem('status').value==='sale')f.elements.namedItem('status').value='available';syncVehiclePrices({preserveMcScrap})}
function openVehicle(v){const f=$('#vehicleForm'),field=name=>f.elements.namedItem(name);f.reset();$('#vehicleDialogTitle').textContent=v?'Изменить транспорт':'Добавить транспорт';field('editId').value=v?.id||'';field('catalogId').value=v?.catalogId||'';field('vehicleType').value=v?.vehicleType||'car';field('name').value=v?.name||'';field('plate').value=v?.plate||'';field('purchase').value=inputMoney(v?.purchase);field('govPrice').value=inputMoney(v?.govPrice);field('scrap').value=inputMoney(v?.scrap);field('status').value=v?.status||'available';setPurchaseCurrency(v?.purchaseCurrency||'money',{preserveMcScrap:!!v});$('#photoData').value=v?.photo||'';$('#photoPreview').innerHTML=v?.photo?`<img src="${v.photo}" alt="Фото транспорта">`:'<span>＋</span><b>Выбрать транспорт из каталога</b><small>956 позиций</small>';$('#vehicleDialog').showModal()}

function catalogType(id){for(const type of ['moto','bmx','boat','heli','air','commercial'])if(categorySets[type]?.has(id))return type;return 'car'}
function renderCatalog(){const q=$('#catalogSearch').value.trim().toLowerCase();const filtered=(window.VEHICLE_CATALOG||[]).filter(item=>(catalogCategory==='all'||catalogType(item.id)===catalogCategory)&&item.name.toLowerCase().includes(q));const pages=Math.max(1,Math.ceil(filtered.length/CATALOG_PAGE_SIZE));catalogPage=Math.min(catalogPage,pages);const start=(catalogPage-1)*CATALOG_PAGE_SIZE;$('#catalogGrid').innerHTML=filtered.slice(start,start+CATALOG_PAGE_SIZE).map(item=>`<button type="button" class="catalog-card" data-catalog-id="${esc(item.id)}"><div><img loading="lazy" src="${esc(item.image)}" alt="${esc(item.name)}"><span>${esc(item.name).split(' ').slice(-1)[0].slice(0,3).toUpperCase()}</span></div><b>${esc(item.name)}</b><small>${({car:'Автомобиль',commercial:'Коммерческий',moto:'Мотоцикл',bmx:'Велосипед',boat:'Водный транспорт',heli:'Вертолёт',air:'Самолёт'})[catalogType(item.id)]}</small></button>`).join('')||'<div class="empty">Ничего не найдено</div>';$('#catalogCount').textContent=`Найдено: ${filtered.length}`;$('#catalogPage').textContent=`${catalogPage} / ${pages}`;$('#catalogPrev').disabled=catalogPage<=1;$('#catalogNext').disabled=catalogPage>=pages}
function openCatalog(){catalogPage=1;$('#catalogSearch').value='';renderCatalog();$('#catalogDialog').showModal()}
function selectCatalogItem(id){const item=(window.VEHICLE_CATALOG||[]).find(x=>x.id===id);if(!item)return;const f=$('#vehicleForm');f.elements.namedItem('catalogId').value=item.id;f.elements.namedItem('vehicleType').value=catalogType(item.id);f.elements.namedItem('name').value=item.name;const prices=catalogPrices(item.id);f.elements.namedItem('govPrice').value=inputMoney(prices.govPrice);syncVehiclePrices();$('#photoData').value=item.image;$('#photoPreview').innerHTML=`<img src="${item.image}" alt="${esc(item.name)}">`;$('#catalogDialog').close();toast(prices.govPrice?'Транспорт и госцена выбраны':'Транспорт выбран — госцена пока не найдена')}

function setRentalUnit(unit){const form=$('#rentalForm'),daily=unit==='day',max=daily?30:48;form.elements.namedItem('unit').value=unit;$$('[data-rental-unit]').forEach(b=>b.classList.toggle('active',b.dataset.rentalUnit===unit));$('#rentalPriceLabel').childNodes[0].nodeValue=daily?'Цена за сутки':'Цена за час';$('#rentalDurationLabel').childNodes[0].nodeValue=daily?'Количество суток':'Количество часов';const duration=form.elements.namedItem('duration');duration.max=max;duration.value=1}

function syncQuickAdd(view){const button=$('#quickAdd'),config=view==='garage'?{label:'+ Добавить авто',action:'vehicle'}:null;button.hidden=!config;if(config){button.textContent=config.label;button.dataset.action=config.action}}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${b.dataset.view}View`).classList.add('active');$('#viewTitle').textContent=({dashboard:'Главная',garage:'Ваш автопарк',rentals:'Центр аренды',deals:'Финансовый журнал',encyclopedia:'Энциклопедия',reseller:'Калькулятор прибыли',photos:'Редактор фотографий'}[b.dataset.view]);syncQuickAdd(b.dataset.view)});
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){close.closest('dialog')?.close();return}const jump=e.target.closest('[data-jump]');if(jump)$(`.nav-item[data-view="${jump.dataset.jump}"]`).click();const rent=e.target.closest('[data-rent]');if(rent&&!rent.disabled)openRental(rent.dataset.rent);const edit=e.target.closest('[data-edit-car]');if(edit)openVehicle(vehicle(edit.dataset.editCar));const editAsset=e.target.closest('[data-edit-asset]');if(editAsset)openAsset(state.assets.find(item=>item.id===editAsset.dataset.editAsset));const deleteAsset=e.target.closest('[data-delete-asset]');if(deleteAsset&&confirm('Удалить объект из основного имущества?')){state.assets=state.assets.filter(item=>item.id!==deleteAsset.dataset.deleteAsset);save();toast('Объект удалён')}const saveAd=e.target.closest('[data-save-ad]');if(saveAd){const v=vehicle(saveAd.dataset.saveAd);if(v){v.advert=$(`[data-ad-input="${v.id}"]`).value.trim();save();toast('Текст объявления сохранён')}return}const copy=e.target.closest('[data-copy-ad]');if(copy&&!copy.disabled)copyAdvert(copy.dataset.copyAd);const del=e.target.closest('[data-delete-car]');if(del&&confirm('Удалить автомобиль из гаража?')){state.vehicles=state.vehicles.filter(v=>v.id!==del.dataset.deleteCar);save()}const ret=e.target.closest('[data-return]');if(ret)returnRental(ret.dataset.return);const ext=e.target.closest('[data-extend]');if(ext){const r=state.rentals.find(x=>x.id===ext.dataset.extend);r.end+=864e5;save();toast('Аренда продлена на 24 часа')}const dd=e.target.closest('[data-delete-deal]');if(dd&&confirm('Удалить операцию?')){state.deals=state.deals.filter(d=>d.id!==dd.dataset.deleteDeal);save()}});
document.addEventListener('input',e=>{if(!e.target.matches('[data-money]'))return;const digits=e.target.value.replace(/\D/g,'');e.target.value=digits?Number(digits).toLocaleString('ru-RU'):''});
$('#garageSearch').addEventListener('input',renderGarage);$('#garageFilter').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;currentFilter=b.dataset.filter;$$('#garageFilter button').forEach(x=>x.classList.toggle('active',x===b));renderGarage()});
$('#quickAdd').addEventListener('click',event=>event.currentTarget.dataset.action==='asset'?openAsset():openVehicle());
$('#newAssetBtn').addEventListener('click',()=>$('#assetTypeDialog').showModal());
$('#assetEditToggle').addEventListener('click',()=>{assetEditMode=!assetEditMode;$('#assetEditToggle').classList.toggle('active',assetEditMode);renderAssets();toast(assetEditMode?'Режим управления включён':'Режим управления выключен')});
$('#assetTypeDialog').addEventListener('click',event=>{const button=event.target.closest('[data-new-asset-type]');if(!button)return;$('#assetTypeDialog').close();openAsset(null,button.dataset.newAssetType)});
$('#assetForm').elements.namedItem('type').addEventListener('change',event=>{$('#assetNameSearch').value='';syncAssetNameOptions();renderAssetUpgradePicker(event.target.value)});
$('#assetNameSearch').addEventListener('input',()=>renderAssetNameOptions());
$('#assetGarageFilter').addEventListener('change',()=>renderAssetNameOptions());
$('#assetNameSelect').addEventListener('change',event=>{const form=$('#assetForm'),option=event.target.selectedOptions[0],levels=readAssetUpgradeLevels();form.elements.namedItem('catalogId').value=option?.dataset.catalogId||'';if(event.target.value)$('#assetNameSearch').value=event.target.value;renderAssetUpgradePicker(form.elements.namedItem('type').value,levels,findAssetCatalogItem(form.elements.namedItem('type').value,form.elements.namedItem('catalogId').value,event.target.value))});
$('#assetUpgradeGrid').addEventListener('change',event=>{if(!event.target.matches('select'))return;event.target.closest('[data-asset-upgrade-card]')?.classList.toggle('active',+event.target.value>0)});
$('#assetForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),value=parseMoney(data.value),taxPerDay=parseMoney(data.taxPerDay),paidUntil=data.paidUntil?new Date(data.paidUntil+'T23:59:59').getTime():0,name=data.name.trim(),upgradeLevels=readAssetUpgradeLevels(),upgrades=assetUpgradeText(upgradeLevels);if(!name)return toast('Выберите имущество из списка');if(!value)return toast('Укажите стоимость имущества');state.assets??=[];const fields={type:data.type,catalogId:data.catalogId||'',name,value,taxPerDay,paidUntil,taxSyncedAt:paidUntil?Date.now():0,upgradeLevels,upgrades};if(data.editId){const item=state.assets.find(asset=>asset.id===data.editId);if(item){delete item.note;Object.assign(item,fields)}}else state.assets.push({id:uid('a'),...fields,createdAt:Date.now()});state.taxNotices={};$('#assetDialog').close();save();toast(data.editId?'Имущество обновлено':'Имущество добавлено')});
document.addEventListener('click',event=>{const button=event.target.closest('[data-pay-tax]');if(button&&!button.disabled)openTaxPayment((state.assets||[]).find(item=>item.id===button.dataset.payTax))});
document.addEventListener('click',event=>{const button=event.target.closest('[data-dispose-asset]');if(button)openAssetDisposal((state.assets||[]).find(item=>item.id===button.dataset.disposeAsset))});
document.addEventListener('click',event=>{const button=event.target.closest('[data-sync-tax]');if(!button)return;const item=(state.assets||[]).find(asset=>asset.id===button.dataset.syncTax);if(!item)return;const current=Math.max(0,Math.ceil(((+item.paidUntil||0)-Date.now())/864e5)),entered=prompt(`Сколько полных дней сейчас показывает игра для «${item.name}»?`,String(current));if(entered===null)return;const days=Math.max(0,Math.min(30,Number(String(entered).replace(',','.'))||0));item.paidUntil=Date.now()+days*864e5;item.taxSyncedAt=Date.now();state.taxNotices={};save();toast(`Срок сверен: ${days} дн.`)});
$('#taxForm').elements.namedItem('days').addEventListener('input',renderTaxPaymentPreview);
$('#taxForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),item=(state.assets||[]).find(asset=>asset.id===data.assetId);if(!item)return;const now=Date.now(),base=Math.max(now,+item.paidUntil||0),maxUntil=now+30*864e5,allowed=Math.max(0,Math.floor((maxUntil-base)/864e5)),days=Math.min(Math.max(1,+data.days||1),allowed);if(days<1)return toast('Имущество уже оплачено на максимальные 30 дней');const amount=days*(+item.taxPerDay||0);if(state.cash<amount&&!confirm(`На свободном балансе не хватает ${money(amount-state.cash)}. Всё равно провести оплату?`))return;item.paidUntil=base+days*864e5;item.taxSyncedAt=Date.now();state.cash-=amount;state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'expense',vehicleId:'',vehicleName:item.name,amount,note:`Налог на ${item.name} за ${days} дн.`});state.taxNotices={};$('#taxDialog').close();save();toast(`Налог оплачен на ${days} дн.`)});
$('#assetDisposeForm').elements.namedItem('operation').addEventListener('change',syncAssetDisposal);
$('#assetDisposeForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),item=(state.assets||[]).find(asset=>asset.id===data.assetId);if(!item)return;const exchange=data.operation==='exchange',amount=exchange?0:parseMoney(data.amount);if(!exchange&&!amount)return toast('Укажите сумму продажи');state.assets=state.assets.filter(asset=>asset.id!==item.id);for(const key of Object.keys(state.taxNotices||{}))if(key.startsWith(item.id+':'))delete state.taxNotices[key];if(exchange){state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'expense',vehicleId:'',vehicleName:item.name,amount:0,note:`Имущество передано в обмен: ${item.name}`})}else{state.cash+=amount;state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'sale',vehicleId:'',vehicleName:item.name,amount,note:`Продажа имущества: ${item.name}`})}$('#assetDisposeDialog').close();save();toast(exchange?'Старое имущество закрыто — добавьте полученный объект':'Имущество продано');if(exchange)setTimeout(()=>openAsset(),120)});
$$('[data-purchase-currency]').forEach(b=>b.addEventListener('click',()=>setPurchaseCurrency(b.dataset.purchaseCurrency)));
$('#photoPreview').addEventListener('click',openCatalog);$('#openCatalogBtn').addEventListener('click',openCatalog);$('#uploadOwnPhoto').addEventListener('click',()=>$('#vehiclePhoto').click());$('#vehiclePhoto').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{$('#photoData').value=r.result;$('#photoPreview').innerHTML=`<img src="${r.result}" alt="Фото транспорта">`};r.readAsDataURL(f)});
$('#catalogFilters [data-category="moto"]').insertAdjacentHTML('afterend','<button data-category="bmx">Велосипеды</button>');
$('#catalogSearch').addEventListener('input',()=>{catalogPage=1;renderCatalog()});$('#catalogFilters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;catalogCategory=b.dataset.category;catalogPage=1;$$('#catalogFilters button').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$('#catalogGrid').addEventListener('click',e=>{const b=e.target.closest('[data-catalog-id]');if(b)selectCatalogItem(b.dataset.catalogId)});$('#catalogPrev').addEventListener('click',()=>{catalogPage--;renderCatalog()});$('#catalogNext').addEventListener('click',()=>{catalogPage++;renderCatalog()});
$('#vehicleForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),purchase=parseMoney(d.purchase),govPrice=parseMoney(d.govPrice),scrap=parseMoney(d.scrap),purchaseCurrency=d.purchaseCurrency==='mc'?'mc':'money';if(!d.catalogId&&!d.editId)return toast('Сначала выберите транспорт из каталога');if(purchaseCurrency==='mc'&&d.status==='sale')return toast('MC-технику нельзя выставить на продажу игрокам');if(d.editId){const current=vehicle(d.editId);Object.assign(current,{catalogId:d.catalogId,vehicleType:d.vehicleType,name:d.name,plate:d.plate,purchase,purchaseCurrency,govPrice,scrap,status:d.status,photo:$('#photoData').value});toast('Карточка обновлена')}else{state.vehicles.push({id:uid('v'),catalogId:d.catalogId,vehicleType:d.vehicleType,name:d.name,plate:d.plate,purchase,purchaseCurrency,govPrice,scrap,status:d.status,photo:$('#photoData').value,advert:''});if(purchaseCurrency!=='mc')state.cash-=purchase;state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'purchase',vehicleId:state.vehicles.at(-1).id,vehicleName:d.name,amount:purchase,currency:purchaseCurrency,note:purchaseCurrency==='mc'?'Покупка транспорта за Majestic Coin':'Покупка транспорта'});toast(purchaseCurrency==='mc'?'MC-транспорт добавлен':'Транспорт добавлен')}$('#vehicleDialog').close();save()});
$('#newRentalBtn').addEventListener('click',()=>openRental());$('#rentalCarPicker').addEventListener('click',e=>{const b=e.target.closest('[data-pick]');if(!b)return;$('#rentalForm').elements.namedItem('vehicleId').value=b.dataset.pick;$$('.pick-car').forEach(x=>x.classList.toggle('selected',x===b));syncRentalAd()});$('#copyRentalAd').addEventListener('click',()=>copyAdvert($('#rentalForm').elements.namedItem('vehicleId').value));
$$('[data-rental-unit]').forEach(b=>b.addEventListener('click',()=>setRentalUnit(b.dataset.rentalUnit)));
$('#rentalForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!d.vehicleId)return toast('Сначала выберите транспорт');const selected=vehicle(d.vehicleId);if(!selected)return toast('Транспорт не найден');const start=Date.now(),duration=+d.duration,hours=duration*(d.unit==='day'?24:1),price=parseMoney(d.price),total=price*duration;state.rentals.push({id:uid('r'),vehicleId:d.vehicleId,price,total,duration,unit:d.unit,hours,start,end:start+(hours*36e5)});selected.status='rented';$('#rentalDialog').close();save();toast('Аренда запущена')});
function returnRental(id){const r=state.rentals.find(x=>x.id===id);if(!r)return;const v=vehicle(r.vehicleId);if(v)v.status='available';const total=r.total||r.price;state.rentalHistory.push({...r,total,vehicleName:v?.name||'Транспорт',returned:Date.now()});state.deals.push({id:uid('d'),date:new Date().toISOString().slice(0,10),type:'income',vehicleId:r.vehicleId,amount:total,note:'Доход от аренды'});state.cash+=total;state.rentals=state.rentals.filter(x=>x.id!==id);save();toast('Транспорт возвращён, доход записан')}
function syncDealAmount(){const form=$('#dealForm'),type=form.elements.namedItem('type').value,sold=vehicle(form.elements.namedItem('vehicleId').value);if(type==='sale'&&sold?.purchaseCurrency==='mc')form.elements.namedItem('amount').value=inputMoney(sold.scrap)}
$('#newDealBtn').addEventListener('click',()=>{const form=$('#dealForm');form.reset();form.elements.namedItem('date').value=new Date().toISOString().slice(0,10);$('#dealDialog').showModal()});
$('#dealForm').elements.namedItem('type').addEventListener('change',syncDealAmount);$('#dealVehicle').addEventListener('change',syncDealAmount);
$('#dealForm').addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),amount=parseMoney(d.amount),sold=vehicle(d.vehicleId);if(d.type==='sale'&&!sold)return toast('Выберите проданный транспорт');const type=d.type==='sale'&&sold?.purchaseCurrency==='mc'?'scrapSale':d.type,removesVehicle=type==='sale'||type==='scrapSale';state.deals.push({id:uid('d'),...d,type,amount,vehicleName:sold?.name||'',note:d.note||(type==='scrapSale'?'Продажа MC-техники на свалку':'')});state.cash+=removesVehicle?amount:-amount;if(removesVehicle&&sold){state.rentals=state.rentals.filter(r=>r.vehicleId!==sold.id);state.vehicles=state.vehicles.filter(v=>v.id!==sold.id)}$('#dealDialog').close();save();toast(removesVehicle?(type==='scrapSale'?'MC-техника продана на свалку и удалена из гаража':'Продажа записана, транспорт удалён из гаража'):'Покупка добавлена')});
$('#profileSelect').addEventListener('change',e=>{database.activeProfileId=e.target.value;state=getActiveProfile();save();toast(`Профиль «${state.name}» открыт`)});
$('#serverSelect').addEventListener('change',e=>{database.activeServer=e.target.value;let profile=database.profiles.find(p=>p.server===database.activeServer);if(!profile){profile=blankProfile(uid('p'),'Персонаж 1',database.activeServer);database.profiles.push(profile)}database.activeProfileId=profile.id;state=profile;save();toast(`Сервер ${database.activeServer} открыт`)});
$('#addProfileBtn').addEventListener('click',()=>{const form=$('#profileForm');form.reset();$('#profileDialog').showModal();requestAnimationFrame(()=>form.elements.namedItem('name').focus())});
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.target).get('name')?.trim();if(!name)return;const profile=blankProfile(uid('p'),name,database.activeServer);database.profiles.push(profile);database.activeProfileId=profile.id;state=profile;$('#profileDialog').close();save();toast('Персонаж добавлен')});
$('#editBalanceBtn').addEventListener('click',()=>{const input=$('#balanceForm').elements.namedItem('amount');input.value=inputMoney(state.cash);$('#balanceDialog').showModal();requestAnimationFrame(()=>input.select())});
$('#balanceForm').addEventListener('submit',e=>{e.preventDefault();const amount=parseMoney(new FormData(e.target).get('amount'));state.cash=amount;$('#balanceDialog').close();save();toast('Баланс обновлён')});
$('#resetProfileBtn').addEventListener('click',()=>{if(!confirm(`Сбросить всю статистику персонажа «${state.name}»? Это удалит баланс, гараж, аренды и данные калькулятора прибыли.`))return;const index=database.profiles.findIndex(p=>p.id===state.id);database.profiles[index]=blankProfile(state.id,state.name,state.server);state=database.profiles[index];save();toast('Статистика персонажа сброшена')});
$('#themeSelect').addEventListener('change',event=>{localStorage.setItem(THEME_KEY,event.target.value);applyTheme(event.target.value)});
systemTheme.addEventListener('change',()=>{if((localStorage.getItem(THEME_KEY)||'system')==='system')applyTheme('system')});
$('#exportBtn').addEventListener('click',async()=>{const text=JSON.stringify(database,null,2);if(window.desktop)await window.desktop.saveBackup(text);else{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download='fleet-desk.json';a.click()}toast('Резервная копия сохранена')});
$('#importBtn').addEventListener('click',async()=>{let text=window.desktop?await window.desktop.openBackup():null;if(!text)return;try{database=normalizeDatabase(JSON.parse(text));state=getActiveProfile();save();toast('База восстановлена')}catch{toast('Не удалось прочитать файл')}});

const updateLabels={checking:'Проверяем обновления…',available:'Найдена новая версия, скачиваем…',current:'Установлена актуальная версия',downloading:'Загрузка обновления',ready:'Обновление готово',error:'Не удалось проверить обновления',development:'Проверка работает в установленной версии'};
if(window.desktop?.onUpdateStatus)window.desktop.onUpdateStatus(({status,detail})=>{const label=updateLabels[status]||'Обновления';$('#updateStatus').textContent=status==='downloading'?`${label}: ${detail}%`:detail&&['available','ready'].includes(status)?`${label} ${detail}`:label;$('#installUpdateBtn').hidden=status!=='ready'});
$('#checkUpdateBtn').addEventListener('click',()=>window.desktop?.checkForUpdates());
const updateInstallDialog=$('#updateInstallDialog');
updateInstallDialog.addEventListener('cancel',event=>event.preventDefault());
function showInstallStage(title,text,width,step){$('#updateInstallTitle').textContent=title;$('#updateInstallText').textContent=text;$('#updateInstallBar').style.width=width+'%';$$('.update-install-steps span').forEach((item,index)=>item.classList.toggle('active',index<=step))}
$('#installUpdateBtn').addEventListener('click',()=>{if(updateInstallDialog.open)return;showInstallStage('Подготавливаем файлы','Проверяем загруженное обновление Fleet Desk.',18,0);updateInstallDialog.showModal();setTimeout(()=>showInstallStage('Устанавливаем обновление','Всё происходит автоматически — нажимать ничего не нужно.',62,1),550);setTimeout(()=>{showInstallStage('Перезапускаем Fleet Desk','Через несколько секунд откроется обновлённая версия.',100,2);setTimeout(()=>window.desktop?.installUpdate(),450)},1300)});

const cropCanvas=$('#cropCanvas'),cropCtx=cropCanvas.getContext('2d');
let cropImage=null,cropRect=null,cropStart=null,cropDataUrl='';
function loadCropFile(file){if(!file||!file.type.startsWith('image/'))return toast('Выберите изображение');const reader=new FileReader();reader.onload=()=>{const image=new Image();image.onload=()=>{cropImage=image;const maxW=1000,maxH=625,scale=Math.min(maxW/image.width,maxH/image.height,1);cropCanvas.width=Math.round(image.width*scale);cropCanvas.height=Math.round(image.height*scale);const pad=.08;cropRect={x:cropCanvas.width*pad,y:cropCanvas.height*pad,w:cropCanvas.width*(1-pad*2),h:cropCanvas.height*(1-pad*2)};$('#cropEmpty').classList.add('hidden');cropCanvas.classList.add('ready');drawCrop();refreshCropOutput()};image.src=reader.result};reader.readAsDataURL(file)}
function drawCrop(){if(!cropImage)return;cropCtx.clearRect(0,0,cropCanvas.width,cropCanvas.height);cropCtx.drawImage(cropImage,0,0,cropCanvas.width,cropCanvas.height);cropCtx.fillStyle='rgba(3,5,9,.58)';cropCtx.fillRect(0,0,cropCanvas.width,cropCanvas.height);cropCtx.save();cropCtx.beginPath();cropCtx.rect(cropRect.x,cropRect.y,cropRect.w,cropRect.h);cropCtx.clip();cropCtx.drawImage(cropImage,0,0,cropCanvas.width,cropCanvas.height);cropCtx.restore();cropCtx.strokeStyle='#a78bfa';cropCtx.lineWidth=3;cropCtx.strokeRect(cropRect.x,cropRect.y,cropRect.w,cropRect.h)}
function canvasPoint(e){const box=cropCanvas.getBoundingClientRect();return{x:(e.clientX-box.left)*cropCanvas.width/box.width,y:(e.clientY-box.top)*cropCanvas.height/box.height}}
cropCanvas.addEventListener('pointerdown',e=>{if(!cropImage)return;cropStart=canvasPoint(e);cropRect={x:cropStart.x,y:cropStart.y,w:1,h:1};cropCanvas.setPointerCapture(e.pointerId)});
cropCanvas.addEventListener('pointermove',e=>{if(!cropStart)return;const p=canvasPoint(e),ratio=+$('#cropRatio').value;let w=p.x-cropStart.x,h=p.y-cropStart.y;if(ratio){const signY=Math.sign(h)||1;h=Math.abs(w)/ratio*signY}cropRect={x:Math.max(0,Math.min(cropStart.x,cropStart.x+w)),y:Math.max(0,Math.min(cropStart.y,cropStart.y+h)),w:Math.min(Math.abs(w),cropCanvas.width-Math.max(0,Math.min(cropStart.x,cropStart.x+w))),h:Math.min(Math.abs(h),cropCanvas.height-Math.max(0,Math.min(cropStart.y,cropStart.y+h)))};drawCrop()});
cropCanvas.addEventListener('pointerup',()=>{cropStart=null;refreshCropOutput()});
function makeCrop(){if(!cropImage||!cropRect||cropRect.w<5||cropRect.h<5)return null;const sourceScale=cropImage.width/cropCanvas.width;const out=document.createElement('canvas'),outW=+$('#cropWidth').value,outH=Math.round(outW*(cropRect.h/cropRect.w));out.width=outW;out.height=outH;out.getContext('2d').drawImage(cropImage,cropRect.x*sourceScale,cropRect.y*sourceScale,cropRect.w*sourceScale,cropRect.h*sourceScale,0,0,outW,outH);const format=$('#cropFormat').value,quality=+$('#cropQuality').value/100;return{data:out.toDataURL(format,quality),format,width:outW,height:outH}}
function refreshCropOutput(){const result=makeCrop();if(!result)return;cropDataUrl=result.data;const bytes=Math.round((result.data.length-result.data.indexOf(',')-1)*.75);$('#cropSize').textContent=`${result.width}×${result.height} • ${bytes>1048576?(bytes/1048576).toFixed(2)+' МБ':Math.round(bytes/1024)+' КБ'}`;$('#saveCrop').disabled=false;$('#useCropAsPhoto').disabled=false}
function resetCropEditor(){cropImage=null;cropRect=null;cropStart=null;cropDataUrl='';cropCtx.clearRect(0,0,cropCanvas.width,cropCanvas.height);cropCanvas.width=1000;cropCanvas.height=625;cropCanvas.classList.remove('ready');$('#cropEmpty').classList.remove('hidden');$('#cropFile').value='';$('#cropSize').textContent='—';$('#saveCrop').disabled=true;$('#useCropAsPhoto').disabled=true}
$('#openCropImage').addEventListener('click',()=>$('#cropFile').click());$('#cropFile').addEventListener('change',e=>loadCropFile(e.target.files[0]));
const cropStage=$('.crop-stage');['dragenter','dragover'].forEach(x=>cropStage.addEventListener(x,e=>{e.preventDefault();cropStage.classList.add('drag')}));['dragleave','drop'].forEach(x=>cropStage.addEventListener(x,e=>{e.preventDefault();cropStage.classList.remove('drag')}));cropStage.addEventListener('drop',e=>loadCropFile(e.dataTransfer.files[0]));
['cropFormat','cropWidth','cropRatio'].forEach(id=>$(`#${id}`).addEventListener('change',refreshCropOutput));$('#cropQuality').addEventListener('input',e=>{$('#qualityValue').textContent=e.target.value+'%';refreshCropOutput()});
$('#saveCrop').addEventListener('click',async()=>{const result=makeCrop();if(!result)return;if(window.desktop){const path=await window.desktop.saveImage({base64:result.data,format:result.format,filename:'majestic-car-'+Date.now()});if(path){resetCropEditor();toast('Фотография сохранена')}}else{const a=document.createElement('a');a.href=result.data;a.download=result.format==='image/png'?'majestic-car.png':'majestic-car.jpg';a.click();resetCropEditor();toast('Фотография сохранена')}});
$('#useCropAsPhoto').addEventListener('click',()=>{if(!cropDataUrl)return;openVehicle();$('#photoData').value=cropDataUrl;$('#photoPreview').innerHTML=`<img src="${cropDataUrl}" alt="Фото автомобиля">`;toast('Фото перенесено в карточку')});

const resellerCategoryNames={vehicles:'Автомобили',homes:'Недвижимость',items:'Предметы',clothes:'Одежда',atms:'Банкоматы',businesses:'Бизнесы',offices:'Офисы и склады'};
let resellerPickerKind='vehicles',resellerPickerItems=[],resellerPickerSelected=null,resellerPickerPage=1,resellerPickerHasMore=false,resellerPickerTimer,resellerPickerRequest=0,resellerPickerLoading=false;
const WIKI_LOCAL_KEY='fleet-wiki-catalog-v1';
const readLocalCatalog=()=>{try{return JSON.parse(localStorage.getItem(WIKI_LOCAL_KEY))||{}}catch{return{}}};
const writeLocalCatalog=value=>localStorage.setItem(WIKI_LOCAL_KEY,JSON.stringify(value));
const catalogWarmers=new Map();
function localCatalogItems(kind){return readLocalCatalog()[kind]?.items||[]}
function filterLocalCatalog(kind,q){const needle=q.trim().toLocaleLowerCase('ru-RU');return localCatalogItems(kind).map(item=>{const matchedVariant=needle?(item.variants||[]).find(variant=>(variant.name||'').toLocaleLowerCase('ru-RU').includes(needle)):null;return{...item,_matchedVariant:matchedVariant||null,_baseMatches:!needle||`${item.name} ${item.id} ${(item.details||[]).join(' ')}`.toLocaleLowerCase('ru-RU').includes(needle)}}).filter(item=>item._baseMatches||item._matchedVariant)}
function warmLocalCatalog(kind,force=false){
  if(kind==='vehicles'||catalogWarmers.has(kind)||!window.desktop?.getWikiCatalog)return catalogWarmers.get(kind);
  const job=(async()=>{
    const initial=readLocalCatalog()[kind]||{},hadCatalog=!!(initial.complete&&initial.items?.length),known=new Set((initial.items||[]).map(x=>`${x.id}:${x.name}`)),newItems={...(initial.newItems||{})};
    const cutoff=Date.now()-30*864e5;for(const [key,at] of Object.entries(newItems))if(at<cutoff)delete newItems[key];
    let page=force?1:(initial.nextPage||1),hasMore=force?!initial.syncing:!initial.complete;
    if(force)hasMore=true;
    while(hasMore){
      const data=await window.desktop.getWikiCatalog(kind,'',page),store=readLocalCatalog(),saved=store[kind]||{},merged=new Map((saved.items||[]).map(x=>[`${x.id}:${x.name}`,x]));
      for(const item of data.items||[]){const key=`${item.id}:${item.name}`;if(hadCatalog&&!known.has(key))newItems[key]=Date.now();merged.set(key,item)}
      hasMore=!!data.hasMore;
      store[kind]={items:[...merged.values()],complete:!hasMore,nextPage:page+1,newItems,updatedAt:Date.now()};writeLocalCatalog(store);
      if(resellerPickerKind===kind&&$('#resellerDealDialog').open){const q=$('#resellerDealSearch').value.trim();resellerPickerItems=filterLocalCatalog(kind,q).slice(0,400);renderResellerPicker()}
      page++;if(page>250)break;
    }
  })().catch(()=>{}).finally(()=>catalogWarmers.delete(kind));
  catalogWarmers.set(kind,job);return job;
}
async function syncAllLocalCatalogs(){for(const kind of ['items','clothes','homes','offices','businesses','atms'])await warmLocalCatalog(kind,true)}
function renderResellerPicker(){const grid=$('#resellerPickerGrid');grid.innerHTML=resellerPickerItems.map((item,index)=>`<button type="button" class="reseller-picker-card ${String(resellerPickerSelected?.sourceId||'').split('::')[0]===String(item.id)?'active':''}" data-reseller-pick="${index}">${item._matchedVariant?.image||item.image?`<img loading="lazy" src="${esc(item._matchedVariant?.image||item.image)}" alt="">`:'<span class="reseller-picker-image">◈</span>'}<span><b>${esc(item.name)}</b><small>${item._matchedVariant?`Расцветка: ${esc(item._matchedVariant.name)}`:esc(item.price||item.details?.[0]||resellerCategoryNames[resellerPickerKind])}</small></span></button>`).join('')||'<div class="empty">Ничего не найдено</div>';$('#resellerPickerMore').hidden=!resellerPickerHasMore}
async function loadResellerPicker(append=false){
  const q=$('#resellerDealSearch').value.trim(),kind=resellerPickerKind;
  if(append&&resellerPickerLoading)return;
  const request=append?resellerPickerRequest:++resellerPickerRequest;
  if(!append){resellerPickerPage=1;resellerPickerItems=[];resellerPickerSelected=null;$('#resellerSelected').textContent='Сначала выберите позицию из списка'}
  resellerPickerLoading=true;
  $('#resellerPickerGrid').innerHTML='<div class="empty">Загружаю каталог…</div>';
  if(kind==='vehicles'){
    const items=(window.VEHICLE_CATALOG||[]).filter(x=>`${x.name} ${x.id}`.toLowerCase().includes(q.toLowerCase())).slice(0,240).map(x=>({...x,price:''}));
    if(request!==resellerPickerRequest||kind!==resellerPickerKind)return;
    resellerPickerItems=items;resellerPickerHasMore=false;resellerPickerLoading=false;renderResellerPicker();return;
  }
  const local=filterLocalCatalog(kind,q);
  if(local.length||readLocalCatalog()[kind]){resellerPickerItems=local.slice(0,400);resellerPickerHasMore=false;resellerPickerLoading=false;renderResellerPicker();warmLocalCatalog(kind);return}
  try{
    const page=1,data=await window.desktop.getWikiCatalog(kind,'',page);
    if(request!==resellerPickerRequest||kind!==resellerPickerKind||q!==$('#resellerDealSearch').value.trim())return;
    const store=readLocalCatalog();store[kind]={items:data.items||[],complete:!data.hasMore,nextPage:2,updatedAt:Date.now()};writeLocalCatalog(store);
    resellerPickerItems=filterLocalCatalog(kind,q).slice(0,400);resellerPickerHasMore=false;
    renderResellerPicker();
    warmLocalCatalog(kind);
  }catch(error){if(request===resellerPickerRequest)$('#resellerPickerGrid').innerHTML=`<div class="empty">Не удалось загрузить: ${esc(error?.message||'ошибка сети')}</div>`}
  finally{if(request===resellerPickerRequest)resellerPickerLoading=false}
}
const resellerOperationSelect=$('#resellerDealForm').elements.namedItem('operation');
const resellerOperationSwitch=document.createElement('div');
resellerOperationSwitch.className='reseller-operation-switch';
resellerOperationSwitch.innerHTML='<button type="button" data-operation="purchase">Покупка</button><button type="button" data-operation="sale">Продажа</button>';
resellerOperationSelect.before(resellerOperationSwitch);
resellerOperationSelect.hidden=true;
const resellerQuantityInput=$('#resellerDealForm').elements.namedItem('quantity');
const resellerUnitPriceInput=$('#resellerDealForm').elements.namedItem('unitPrice');
const resellerUnitMode=document.createElement('label');
resellerUnitMode.className='reseller-unit-mode';
resellerUnitMode.innerHTML='Формат покупки<div class="reseller-mini-switch"><button type="button" class="active" data-unit-mode="piece">Штучно</button><button type="button" data-unit-mode="stack">Стаком</button></div><input type="hidden" name="unitMode" value="piece">';
resellerQuantityInput.closest('label').before(resellerUnitMode);
const resellerPackSize=document.createElement('label');
resellerPackSize.className='reseller-pack-size';
resellerPackSize.innerHTML='Штук в стаке<input name="packSize" type="number" min="2" value="30">';
resellerPackSize.hidden=true;
resellerQuantityInput.closest('label').after(resellerPackSize);
const resellerSaleChannel=document.createElement('label');resellerSaleChannel.className='reseller-sale-channel';resellerSaleChannel.innerHTML='Способ продажи<div class="reseller-mini-switch"><button type="button" class="active" data-sale-channel="hands">На руки</button><button type="button" data-sale-channel="marketplace">Маркетплейс</button></div><input type="hidden" name="saleChannel" value="hands">';resellerUnitMode.after(resellerSaleChannel);
const resellerCommission=document.createElement('div');resellerCommission.className='reseller-commission-preview';resellerCommission.hidden=true;resellerSaleChannel.after(resellerCommission);
function renderResellerCommission(){const form=$('#resellerDealForm'),marketplace=resellerOperationSelect.value==='sale'&&form.elements.namedItem('saleChannel').value==='marketplace',gross=Math.max(1,+resellerQuantityInput.value||1)*parseMoney(resellerUnitPriceInput.value),fee=resellerMarketplaceFee(gross);resellerCommission.hidden=!marketplace;if(marketplace)resellerCommission.innerHTML=`<span>Комиссия: <b>3%, максимум $250 000</b></span><span>Продажа <b>${money(gross)}</b> · комиссия <b class="negative">−${money(fee)}</b> · получите <b class="positive">${money(gross-fee)}</b></span>`}
function syncResellerUnitMode(){const form=$('#resellerDealForm'),isPurchase=resellerOperationSelect.value==='purchase',supportsStacks=resellerPickerKind==='items';if(!supportsStacks)form.elements.namedItem('unitMode').value='piece';const mode=form.elements.namedItem('unitMode').value,stack=mode==='stack'&&isPurchase&&supportsStacks,channel=form.elements.namedItem('saleChannel').value;resellerUnitMode.hidden=!isPurchase||!supportsStacks;resellerPackSize.hidden=!stack;resellerSaleChannel.hidden=isPurchase;resellerUnitMode.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.unitMode===mode));resellerSaleChannel.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.saleChannel===channel));resellerQuantityInput.closest('label').childNodes[0].textContent=stack?'Количество стаков':'Количество';resellerUnitPriceInput.closest('label').childNodes[0].textContent=stack?'Цена за стак':'Цена за штуку';renderResellerCommission()}
function syncResellerOperation(){resellerOperationSwitch.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.operation===resellerOperationSelect.value));syncResellerUnitMode()}
resellerOperationSwitch.addEventListener('click',event=>{const button=event.target.closest('[data-operation]');if(!button)return;resellerOperationSelect.value=button.dataset.operation;syncResellerOperation()});
resellerUnitMode.addEventListener('click',event=>{const button=event.target.closest('[data-unit-mode]');if(!button)return;$('#resellerDealForm').elements.namedItem('unitMode').value=button.dataset.unitMode;syncResellerUnitMode()});
resellerSaleChannel.addEventListener('click',event=>{const button=event.target.closest('[data-sale-channel]');if(!button)return;$('#resellerDealForm').elements.namedItem('saleChannel').value=button.dataset.saleChannel;syncResellerUnitMode()});
[resellerQuantityInput,resellerUnitPriceInput].forEach(input=>input.addEventListener('input',renderResellerCommission));
new MutationObserver(()=>{if($('#resellerDealDialog').open)syncResellerOperation()}).observe($('#resellerDealDialog'),{attributes:true,attributeFilter:['open']});
function openResellerDeal(selected=null,operation='purchase'){const form=$('#resellerDealForm');form.reset();form.elements.namedItem('operation').value=operation;resellerPickerKind=selected?.sourceType||'vehicles';resellerPickerSelected=selected;$$('#resellerCategoryTabs button').forEach(x=>x.classList.toggle('active',x.dataset.resellerKind===resellerPickerKind));$('#resellerDealSearch').value=selected?.name||'';$('#resellerSelected').innerHTML=selected?`Выбрано: <b>${esc(selected.name)}</b> · ${esc(selected.category||resellerCategoryNames[resellerPickerKind])}`:'Сначала выберите позицию из списка';$('#resellerDealDialog').showModal();loadResellerPicker().then(()=>{if(!selected)return;resellerPickerSelected=selected;$('#resellerSelected').innerHTML=`Выбрано: <b>${esc(selected.name)}</b> · ${esc(selected.category||resellerCategoryNames[resellerPickerKind])}`;renderResellerPicker()})}
$('#newResellerDealBtn').addEventListener('click',()=>openResellerDeal());
const workIncomeJob=$('#workIncomeJob'),workIncomeCustomLabel=$('#workIncomeCustomLabel'),workIncomeCustomInput=$('#workIncomeForm').elements.namedItem('customName');
function syncWorkIncomeJob(){const custom=workIncomeJob.value==='other';workIncomeCustomLabel.hidden=!custom;workIncomeCustomInput.required=custom;if(!custom)workIncomeCustomInput.value=''}
workIncomeJob.addEventListener('change',syncWorkIncomeJob);
$('#newWorkIncomeBtn').addEventListener('click',()=>{const form=$('#workIncomeForm');form.reset();form.elements.namedItem('date').value=new Date().toISOString().slice(0,10);syncWorkIncomeJob();$('#workIncomeDialog').showModal()});
$('#workIncomeForm').addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget)),amount=parseMoney(data.amount),name=(data.job==='other'?data.customName:data.job).trim();if(!name)return toast('Выберите работу');if(!amount)return toast('Укажите сумму дохода');rememberResellerAction(`доход с работы «${name}»`);state.workIncomes??=[];state.workIncomes.push({id:uid('w'),name,amount,date:data.date,at:new Date(data.date+'T12:00:00').getTime()});persistReseller();renderReseller();$('#workIncomeDialog').close();toast('Доход с работы добавлен')});
$('#resellerUndoBtn').addEventListener('click',undoResellerAction);
$('#resellerHistoryBtn').addEventListener('click',()=>{renderResellerReports();$('#resellerHistoryDialog').showModal()});
$('#resellerStatsBtn').addEventListener('click',()=>{renderResellerReports();$('#resellerStatsDialog').showModal()});
$('#resellerCategoryTabs').addEventListener('click',e=>{const button=e.target.closest('[data-reseller-kind]');if(!button)return;resellerPickerKind=button.dataset.resellerKind;$$('#resellerCategoryTabs button').forEach(x=>x.classList.toggle('active',x===button));syncResellerUnitMode();loadResellerPicker()});
$('#resellerDealSearch').addEventListener('input',()=>{clearTimeout(resellerPickerTimer);resellerPickerTimer=setTimeout(()=>loadResellerPicker(),350)});
$('#resellerPickerMore').addEventListener('click',()=>loadResellerPicker(true));
$('#resellerPickerGrid').addEventListener('scroll',event=>{const grid=event.currentTarget;if(!resellerPickerHasMore||grid.scrollTop+grid.clientHeight<grid.scrollHeight-100)return;loadResellerPicker(true)});
let pendingClothingItem=null;
function selectResellerItem(item,variant=null){const variantName=variant?.name||'',image=variant?.image||item.image||'',sourceId=variantName?`${item.id}::${variantName}`:String(item.id),name=variantName?`${item.name} — ${variantName}`:item.name;resellerPickerSelected={sourceType:resellerPickerKind,sourceId,name,image,category:resellerCategoryNames[resellerPickerKind],variantName};$('#resellerSelected').innerHTML=`Выбрано: <b>${esc(item.name)}</b>${variantName?` · Расцветка: <b>${esc(variantName)}</b>`:''} · ${esc(resellerCategoryNames[resellerPickerKind])}`;renderResellerPicker()}
$('#resellerPickerGrid').addEventListener('click',e=>{const button=e.target.closest('[data-reseller-pick]');if(!button)return;const item=resellerPickerItems[+button.dataset.resellerPick];if(resellerPickerKind==='clothes'&&item.variants?.length>1){pendingClothingItem=item;const variants=item._matchedVariant&&!item._baseMatches?[item._matchedVariant]:item.variants;$('#clothingVariantTitle').textContent=item.name;$('#clothingVariantGrid').innerHTML=variants.map(variant=>{const index=item.variants.indexOf(variant);return`<button type="button" class="clothing-variant-card" data-clothing-variant="${index}"><img src="${esc(variant.image||item.image||'')}" alt=""><b>${esc(variant.name||`Расцветка ${index+1}`)}</b></button>`}).join('');$('#clothingVariantDialog').showModal();return}selectResellerItem(item,item._matchedVariant)});
$('#clothingVariantGrid').addEventListener('click',event=>{const button=event.target.closest('[data-clothing-variant]');if(!button||!pendingClothingItem)return;const variant=pendingClothingItem.variants[+button.dataset.clothingVariant];selectResellerItem(pendingClothingItem,variant);pendingClothingItem=null;$('#clothingVariantDialog').close();requestAnimationFrame(()=>resellerUnitPriceInput.focus())});
$('#resellerDealForm').addEventListener('submit',e=>{e.preventDefault();if(!resellerPickerSelected)return toast('Сначала выберите позицию');const data=Object.fromEntries(new FormData(e.target)),enteredQty=Math.max(1,Number(data.quantity)||1),unit=parseMoney(data.unitPrice),isStack=data.operation==='purchase'&&data.unitMode==='stack',packSize=isStack?Math.max(2,Number(data.packSize)||30):1,qty=enteredQty*packSize;if(!unit)return toast(isStack?'Укажите цену за стак':'Укажите цену за штуку');rememberResellerAction(`${data.operation==='purchase'?'покупку':'продажу'} «${resellerPickerSelected.name}»`);state.resellerItems??=[];let item=state.resellerItems.find(x=>x.sourceType===resellerPickerSelected.sourceType&&x.sourceId===resellerPickerSelected.sourceId);if(!item){item={id:uid('r'),...resellerPickerSelected,buyQty:0,buyUnit:0,buyCost:0,purchases:[],sales:[],createdAt:Date.now()};state.resellerItems.push(item)}if(data.operation==='purchase'){const oldQty=+item.buyQty||0,oldCost=item.buyCost==null?oldQty*(+item.buyUnit||0):(+item.buyCost||0),newQty=oldQty+qty,newCost=oldCost+enteredQty*unit;item.buyQty=newQty;item.buyCost=newCost;item.buyUnit=newQty?newCost/newQty:0;item.purchases??=[];item.purchases.push({qty,enteredQty,unit,unitMode:isStack?'stack':'piece',packSize,at:Date.now()})}else{item.sales??=[];item.sales.push({qty,unit,channel:data.saleChannel==='marketplace'?'marketplace':'hands',at:Date.now()});if(resellerTotals(item).remaining===0)archiveResellerItem(item,Date.now())}persistReseller();renderReseller();$('#resellerDealDialog').close();toast(data.operation==='purchase'?(isStack?`Добавлено: ${enteredQty} стак. (${qty} шт.)`:'Покупка добавлена'):(data.saleChannel==='marketplace'?'Продажа записана с комиссией 3%':'Продажа на руки записана'))});

$('#resellerList').addEventListener('click',e=>{const card=e.target.closest('[data-reseller-card]');if(!card)return;const item=state.resellerItems.find(x=>x.id===card.dataset.resellerCard);if(!item)return;if(e.target.closest('[data-reseller-delete]')){rememberResellerAction(`удаление «${item.name}»`);state.resellerItems=state.resellerItems.filter(x=>x.id!==item.id);persistReseller();renderReseller();return}const source={sourceType:item.sourceType,sourceId:item.sourceId,name:item.name,image:item.image,category:item.category};if(e.target.closest('[data-reseller-buy]'))openResellerDeal(source,'purchase');if(e.target.closest('[data-reseller-sell]'))openResellerDeal(source,'sale')});
$('#resellerList').addEventListener('input',e=>{const card=e.target.closest('[data-reseller-card]');if(!card)return;const item=state.resellerItems.find(x=>x.id===card.dataset.resellerCard);if(!item)return;const own=e.target.dataset.resellerField;if(own)item[own]=own==='buyUnit'?parseMoney(e.target.value):Math.max(0,+e.target.value||0);const saleRow=e.target.closest('[data-sale-index]'),saleField=e.target.dataset.saleField;if(saleRow&&saleField){const sale=item.sales[+saleRow.dataset.saleIndex];sale[saleField]=saleField==='unit'?parseMoney(e.target.value):Math.max(0,+e.target.value||0)}persistReseller();const t=resellerTotals(item);card.querySelector('[data-reseller-total="invested"]').textContent=money(t.invested);card.querySelector('[data-reseller-total="remaining"]').textContent=t.remaining+' шт.';card.querySelector('[data-reseller-total="received"]').textContent=money(t.received);const result=card.querySelector('[data-reseller-total="result"]');result.textContent=(t.result<0?'−':'')+money(Math.abs(t.result));result.classList.toggle('positive',t.result>=0);result.classList.toggle('negative',t.result<0);const saleTotal=e.target.closest('.reseller-sale')?.querySelector('b');if(saleTotal&&saleRow){const s=item.sales[+saleRow.dataset.saleIndex];saleTotal.textContent=money((+s.qty||0)*(+s.unit||0))}const all=state.resellerItems||[],sum=all.reduce((a,x)=>{const z=resellerTotals(x);a.qty+=+x.buyQty||0;a.invested+=z.invested;a.received+=z.received;a.result+=z.result;return a},{qty:0,invested:0,received:0,result:0});const stats=$$('#resellerSummary .reseller-stat b');if(stats.length){stats[0].textContent=all.length;stats[1].textContent=sum.qty;stats[2].textContent=money(sum.invested);stats[3].textContent=money(sum.received);stats[4].textContent=(sum.result<0?'−':'')+money(Math.abs(sum.result));stats[4].classList.toggle('positive',sum.result>=0);stats[4].classList.toggle('negative',sum.result<0)}});

setInterval(updateTimers,1000);renderAll();updateTimers();setTimeout(syncAllLocalCatalogs,1500);setTimeout(checkAssetTaxNotifications,2200);
function scheduleResellerDayRollover(){const now=new Date(),midnight=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);setTimeout(()=>{renderReseller();scheduleResellerDayRollover()},midnight-now+1000)}
scheduleResellerDayRollover();
